"use client";
import {useRef,useState,useEffect} from 'react';
import type {MerchantProductRecord,ProductSpec} from '../../lib/data';
import {DELIVERY_REGIONS,PRODUCT_CATEGORIES,emptyProductRules,normalizeProduct,specCombinations,type ProductRules} from '../../lib/product-rules';
import {ProductImageUpload} from '../product-image-upload';
import {ProductRulesSummary} from '../product-rules-summary';
export function ProductEditor({product,onClose,onSaved,admin=false}:{admin?:boolean;product?:MerchantProductRecord;onClose:()=>void;onSaved:()=>void}){
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const [categories,setCategories]=useState<string[]>(PRODUCT_CATEGORIES),[allowed,setAllowed]=useState(['returns','damage','warranty']),[policyReady,setPolicyReady]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/commerce-policy',{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);setCategories(d.categories);setAllowed(d.guarantees);setPolicyReady(true)}).catch(e=>{if(e.name!=='AbortError')setError('平台规则加载失败，请关闭后重试')});return()=>controller.abort()},[]);
 const dirty=useRef(false),scroll=useRef<HTMLDivElement>(null);
 const [form,setForm]=useState({title:product?.title||'',subtitle:product?.subtitle||'',description:product?.description||'',category:product?.category||'',price:product?.price||'',originalPrice:product?.originalPrice||'',stock:String(product?.stock??0),shippingFee:product?.shippingFee||'0',freeShipping:product?.freeShipping||false,images:(product?.images||[]).join('\n'),promotionTitle:product?.promotionTitle||'',promotionStart:product?.promotionStart?new Date(product.promotionStart).toISOString().slice(0,16):'',promotionEnd:product?.promotionEnd?new Date(product.promotionEnd).toISOString().slice(0,16):''});
 const [specs,setSpecs]=useState<ProductSpec[]>(product?.specifications||[]),[rules,setRules]=useState<ProductRules>(product?.rules?.version===1?product.rules:emptyProductRules());
 const field=(key:keyof typeof form,label:string,type='text')=><label className="block text-xs text-slate-600">{label}<input type={type} value={String(form[key])} onChange={e=>{dirty.current=true;setForm(f=>({...f,[key]:e.target.value}))}} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent p-3 text-base"/></label>;
 const ruleField=(label:string,value:string|number,onChange:(v:string)=>void,type='text')=><label className="block text-xs text-slate-600">{label}<input type={type} value={value} onChange={e=>{dirty.current=true;onChange(e.target.value)}} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent p-3 text-base"/></label>;
 const close=()=>{if(!busy&&!uploading&&(!dirty.current||window.confirm('有未保存的修改，确定关闭？建议先保存草稿。')))onClose()};
 const payload=()=>({...form,images:form.images.split('\n').map(x=>x.trim()).filter(Boolean),specifications:specs,rules,expectedUpdatedAt:product?.updatedAt});
 async function save(publish:boolean){setError('');try{normalizeProduct(payload(),{},publish,categories,allowed)}catch(e){setError((e as Error).message);scroll.current?.scrollTo({top:0});return;}setBusy(true);try{const r=await fetch(product?`/api/${admin?"admin":"merchant"}/products/${product.id}`:'/api/merchant/products',{method:product?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload(),publish,action:publish?'submit':undefined})}),d=await r.json();if(!r.ok)throw Error(d.message||'保存失败');dirty.current=false;onSaved()}catch(e){setError((e as Error).message);scroll.current?.scrollTo({top:0})}finally{setBusy(false)}}
 function changeStep(n:number){setStep(n);setError('');scroll.current?.scrollTo({top:0})}
 function generate(){try{const combos=specCombinations(specs);if(!combos.length)throw Error('请先添加规格');setRules(r=>({...r,variants:combos.map(spec=>r.variants.find(v=>v.spec===spec)||{spec,price:Number(form.price)||0,stock:0,image:''})}));dirty.current=true;setError('')}catch(e){setError((e as Error).message)}}
 return <div role="dialog" aria-modal="true" aria-label={product?'编辑商品':'发布商品'} className="katu-dashboard-dialog fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center"><section className="flex max-h-[94dvh] w-full max-w-2xl flex-col overflow-hidden rounded-t-3xl bg-white sm:rounded-3xl"><header className="shrink-0 border-b p-4"><div className="flex items-center justify-between"><h2 className="font-bold">{product?'编辑商品':'发布商品'}</h2><button disabled={busy||uploading} onClick={close} className="min-h-11 px-3 text-sm">关闭</button></div><p className="text-xs leading-5 text-slate-500">可先保存草稿。修改在售商品后会下架，重新审核后展示。</p><nav className="mt-3 grid grid-cols-4 gap-1">{['基本信息','规格库存','配送保障','预览提交'].map((s,i)=><button key={s} disabled={busy||uploading} onClick={()=>changeStep(i)} aria-current={step===i?'step':undefined} className={`min-h-11 rounded-xl text-xs ${step===i?'bg-slate-700 text-white':'bg-slate-100 text-slate-600'}`}>{i+1}. {s}</button>)}</nav></header>
 <div ref={scroll} className="min-h-0 flex-1 overflow-y-auto p-4">{error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}
 {step===0&&<div className="space-y-4">{field('title','商品名称（提交审核至少4字）')}{field('subtitle','简短卖点（可选）')}<label className="block text-xs text-slate-600">平台分类<select value={form.category} onChange={e=>{dirty.current=true;setForm({...form,category:e.target.value})}} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"><option value="">请选择分类</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-xs text-slate-600">商品说明（至少10字）<textarea value={form.description} rows={5} onChange={e=>{dirty.current=true;setForm({...form,description:e.target.value})}} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"/></label><ProductImageUpload value={form.images} onBusy={setUploading} onChange={images=>{dirty.current=true;setForm(f=>({...f,images}))}}/></div>}
 {step===1&&<div className="space-y-4"><div className="grid grid-cols-2 gap-3">{field('price','基础售价（Ks）','number')}{field('originalPrice','划线原价（可选）','number')}{!specs.length&&field('stock','库存（件）','number')}</div><p className="text-xs leading-6 text-slate-500">无规格商品使用基础售价和库存。有规格时，售价取各组合最低价，总库存自动求和。最多3组规格、100个组合。</p>{specs.map((s,i)=><div key={i} className="space-y-3 rounded-xl border p-3">{ruleField('规格名称（例如颜色）',s.name,v=>{const next=[...specs];next[i]={...s,name:v};setSpecs(next)})}{ruleField('规格值（用顿号分隔，例如红色、蓝色）',s.values.join('、'),v=>{const next=[...specs];next[i]={...s,values:v.split(/[、,，]/)};setSpecs(next)})}<button onClick={()=>{dirty.current=true;setSpecs(specs.filter((_,n)=>i!==n));setRules({...rules,variants:[]})}} className="min-h-11 text-sm text-red-600">删除这组规格</button></div>)}<div className="flex gap-3"><button disabled={specs.length>=3} onClick={()=>{dirty.current=true;setSpecs([...specs,{name:'',values:[]}])}} className="min-h-11 rounded-xl border px-4 text-sm">添加规格</button>{specs.length>0&&<button onClick={generate} className="min-h-11 rounded-xl border px-4 text-sm">生成 / 更新规格组合</button>}</div>{rules.variants.map((v,i)=><div key={v.spec} className="space-y-2 rounded-xl bg-slate-50 p-3"><b className="text-xs">{v.spec}</b><div className="grid grid-cols-2 gap-3">{ruleField('售价（Ks）',v.price,x=>setRules({...rules,variants:rules.variants.map((v,n)=>n===i?{...v,price:Number(x)}:v)}),'number')}{ruleField('库存',v.stock,x=>setRules({...rules,variants:rules.variants.map((v,n)=>n===i?{...v,stock:Number(x)}:v)}),'number')}</div><label className="block text-xs">规格图片（可选）<select value={v.image} onChange={e=>{dirty.current=true;setRules({...rules,variants:rules.variants.map((v,n)=>n===i?{...v,image:e.target.value}:v)})}} className="mt-2 w-full rounded-xl border bg-transparent p-3"><option value="">使用主图</option>{form.images.split('\n').filter(Boolean).map((url,n)=><option key={url} value={url}>图片 {n+1}</option>)}</select></label></div>)}{field('promotionTitle','促销文案（可选）')}{field('promotionStart','促销开始（UTC）','datetime-local')}{field('promotionEnd','促销结束（UTC）','datetime-local')}</div>}
 {step===2&&<div className="space-y-4">{ruleField('发货地点',rules.origin,v=>setRules({...rules,origin:v}))}{ruleField('付款后多少小时内发货（1–720）',rules.dispatchHours,v=>setRules({...rules,dispatchHours:Number(v)}),'number')}<fieldset className="rounded-xl border p-3"><legend className="px-1 text-sm">支持配送的省邦</legend><div className="grid grid-cols-3 gap-2">{DELIVERY_REGIONS.map(r=><label key={r} className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={rules.deliveryRegions.includes(r)} onChange={e=>{dirty.current=true;setRules({...rules,deliveryRegions:e.target.checked?[...rules.deliveryRegions,r]:rules.deliveryRegions.filter(x=>x!==r)})}}/>{r}</label>)}</div></fieldset><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={form.freeShipping} onChange={e=>{dirty.current=true;setForm({...form,freeShipping:e.target.checked})}}/>所选配送地区免运费</label>{!form.freeShipping&&field('shippingFee','每单运费（Ks）','number')}<p className="text-xs text-slate-500">同一店铺多件商品取最高运费；不同店铺运费相加。</p>
 <fieldset className="space-y-3 rounded-xl border p-3"><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" disabled={!allowed.includes("returns")&&!rules.returns.enabled} checked={rules.returns.enabled} onChange={e=>{dirty.current=true;setRules({...rules,returns:{...rules.returns,enabled:e.target.checked}})}}/>支持按约定条件退货</label>{rules.returns.enabled&&<>{ruleField('收货后几天内申请（1–30）',rules.returns.days,v=>setRules({...rules,returns:{...rules.returns,days:Number(v)}}),'number')}{ruleField('退货条件及处理方式',rules.returns.condition,v=>setRules({...rules,returns:{...rules.returns,condition:v}}))}<label className="block text-xs">退货运费承担方<select value={rules.returns.freight} onChange={e=>{dirty.current=true;setRules({...rules,returns:{...rules.returns,freight:e.target.value as 'buyer'|'merchant'}})}} className="mt-2 w-full rounded-xl border bg-transparent p-3"><option value="merchant">商家承担</option><option value="buyer">买家承担（质量问题另行处理）</option></select></label></>}</fieldset>
 <fieldset className="space-y-3 rounded-xl border p-3"><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" disabled={!allowed.includes("damage")&&!rules.damage.enabled} checked={rules.damage.enabled} onChange={e=>{dirty.current=true;setRules({...rules,damage:{...rules.damage,enabled:e.target.checked}})}}/>支持破损补发</label>{rules.damage.enabled&&<>{ruleField('收货后申请时限（天）',rules.damage.days,v=>setRules({...rules,damage:{...rules.damage,days:Number(v)}}),'number')}{ruleField('凭证要求及处理方式',rules.damage.condition,v=>setRules({...rules,damage:{...rules.damage,condition:v}}))}</>}</fieldset>
 <fieldset className="space-y-3 rounded-xl border p-3"><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" disabled={!allowed.includes("warranty")&&!rules.warranty.enabled} checked={rules.warranty.enabled} onChange={e=>{dirty.current=true;setRules({...rules,warranty:{...rules.warranty,enabled:e.target.checked}})}}/>提供店铺保修</label>{rules.warranty.enabled&&<>{ruleField('保修月数',rules.warranty.months,v=>setRules({...rules,warranty:{...rules.warranty,months:Number(v)}}),'number')}{ruleField('保修范围',rules.warranty.scope,v=>setRules({...rules,warranty:{...rules.warranty,scope:v}}))}{ruleField('售后联系方式',rules.warranty.contact,v=>setRules({...rules,warranty:{...rules.warranty,contact:v}}))}</>}</fieldset><p className="text-xs leading-6 text-slate-500">只选择可以履行的承诺。平台认证由管理员配置，商家不能自行声明平台担保。</p></div>}
 {step===3&&<div className="space-y-4">{form.images.split('\n')[0]&&<img src={form.images.split('\n')[0]} alt="商品封面预览" className="aspect-square w-full rounded-xl object-cover"/>}<h3 className="text-lg font-bold">{form.title||'尚未填写商品名称'}</h3><p className="text-sm">{form.category} · Ks {rules.variants.length?Math.min(...rules.variants.map(v=>v.price)):form.price||0}</p><p className="whitespace-pre-wrap text-sm leading-7">{form.description}</p><p className="text-sm">{form.freeShipping?'所选地区免运费':`运费 Ks ${form.shippingFee}`}</p><ProductRulesSummary rules={rules}/>{rules.variants.map(v=><p key={v.spec} className="text-xs">{v.spec} · Ks {v.price} · 库存 {v.stock}</p>)}<p className="rounded-xl bg-slate-50 p-3 text-xs leading-6">提交后进入平台审核，审核通过才会公开展示。已有订单的条款不会随本次修改变化。</p></div>}
 </div><footer className="grid shrink-0 grid-cols-2 gap-3 border-t bg-white p-4 pb-[max(16px,env(safe-area-inset-bottom))]"><button disabled={busy||uploading} onClick={()=>void save(false)} className="min-h-11 rounded-full border text-sm disabled:opacity-40">保存草稿</button><button disabled={busy||uploading||!policyReady} onClick={()=>step===3?void save(true):changeStep(step+1)} className="min-h-11 rounded-full bg-slate-700 text-sm text-white disabled:opacity-40">{busy?'保存中…':step===3?'提交审核':'下一步'}</button></footer></section></div>;
}
