import {saveProduct} from "../../../../lib/product-service";
import {imageUrls} from "../../../../lib/product-images";
import {NextResponse} from "next/server";
import {cleanText,createCommerceId,ensureMerchantSchema,isMerchantRequiredError,requireMerchant} from "../../../../lib/merchant";
export const dynamic="force-dynamic";
const arr=(v:unknown,max=12)=>Array.isArray(v)?v.filter(x=>typeof x==="string").map(x=>cleanText(x,80)).filter(Boolean).slice(0,max):[];
const specs=(v:unknown)=>Array.isArray(v)?v.slice(0,8).map(x=>{const o=x&&typeof x==="object"?x as Record<string,unknown>:{};return{name:cleanText(o.name,40),values:arr(o.values,20)}}).filter(x=>x.name&&x.values.length):[];
const serialize=(r:any)=>({...r,images:Array.isArray(r.images)?r.images:[],tags:Array.isArray(r.tags)?r.tags:[],specifications:Array.isArray(r.specifications)?r.specifications:[],serviceGuarantees:Array.isArray(r.serviceGuarantees)?r.serviceGuarantees:[],createdAt:new Date(r.createdAt).toISOString(),updatedAt:new Date(r.updatedAt).toISOString()});
const fields=`product_rules AS "rules",id,title,subtitle,description,category,price::text,original_price::text AS "originalPrice",stock,status,images,badge,tags,specifications,shipping_fee::text AS "shippingFee",free_shipping AS "freeShipping",service_guarantees AS "serviceGuarantees",promotion_title AS "promotionTitle",promotion_start AS "promotionStart",promotion_end AS "promotionEnd",rejection_reason AS "rejectionReason",is_official AS "isOfficial",is_featured AS "isFeatured",is_recommended AS "isRecommended",sort_order AS "sortOrder",sales_count AS "salesCount",rating_average::text AS "ratingAverage",rating_count AS "ratingCount",created_at AS "createdAt",updated_at AS "updatedAt"`;
export async function GET(){try{const{merchant}=await requireMerchant();const db=await ensureMerchantSchema();const r=await db.query(`SELECT ${fields} FROM products WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 200`,[merchant.id]);return NextResponse.json({products:r.rows.map(serialize)})}catch(e){if(isMerchantRequiredError(e))return NextResponse.json({message:"需要商家权限"},{status:403});return NextResponse.json({message:"商品加载失败"},{status:500})}}
export async function POST(request:Request){try{const {user,merchant}=await requireMerchant();const product=await saveProduct(await request.json(),user.id,merchant.id);return NextResponse.json({product},{status:201});}catch(e){return NextResponse.json({message:e instanceof Error?e.message:"商品创建失败"},{status:isMerchantRequiredError(e)?403:400});}}
