"use client";
import {useEffect,useState} from 'react';
type Review={id:string;productId:string;title:string;spec:string;rating:number;content:string;createdAt:string};
type Pending={orderId:string;orderNo:string;productId:string;title:string;spec:string};
export function ProductReviews({productId,onProduct}:{productId?:string;onProduct?:(id:string)=>void}){
 const[rows,setRows]=useState<Review[]>([]),[pending,setPending]=useState<Pending[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[average,setAverage]=useState<string|null>(null),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[version,setVersion]=useState(0),[edit,setEdit]=useState<Pending|null>(null),[rating,setRating]=useState(5),[content,setContent]=useState(''),[busy,setBusy]=useState(false),[submitError,setSubmitError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/reviews?'+(productId?'productId='+encodeURIComponent(productId):'mine=true')+'&page='+page,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);return d}).then(d=>{if(controller.signal.aborted)return;setRows(d.reviews);setPending(d.pending);setTotal(d.total);setAverage(d.average);setMore(d.hasMore)}).catch(e=>{if(!controller.signal.aborted)setError(e.message||'评价加载失败')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[productId,page,version]);
 async function submit(){if(!edit)return;setBusy(true);setSubmitError('');try{const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:edit.orderId,productId:edit.productId,rating,content})}),d=await r.json();if(!r.ok)throw Error(d.message);setEdit(null);setPage(1);setVersion(v=>v+1)}catch(e){setSubmitError((e as Error).message)}finally{setBusy(false)}}
 return <section id={productId?"product-reviews":undefined} className="scroll-mt-4 space-y-4 rounded-2xl bg-white p-4"><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold">{productId?'商品评价':'历史评价'}{!loading&&!error&&`（${total}）`}</h2>{average&&<span className="text-xs">★ {average} / 5</span>}</div>
 {loading?<p role="status" className="py-4 text-sm text-slate-500">正在加载评价…</p>:error?<div role="alert" className="text-sm"><p>{error}</p><button onClick={()=>setVersion(v=>v+1)} className="mt-2 min-h-11 rounded-full border px-4">重试</button></div>:<>
 {!productId&&pending.length>0&&<div className="space-y-3 border-b pb-4"><h3 className="text-sm font-semibold">待评价（{pending.length}）</h3>{pending.map(p=><div key={p.orderId+p.productId} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="line-clamp-2 text-sm">{p.title}</p><p className="mt-1 text-xs text-slate-500">{p.spec}</p></div><button onClick={()=>{setEdit(p);setRating(5);setContent('');setSubmitError('')}} className="min-h-11 shrink-0 rounded-full border px-3 text-xs">写评价</button></div>)}</div>}
 {rows.length?rows.map(r=><article key={r.id} className="border-b pb-4 last:border-0"><div className="flex flex-wrap items-center justify-between gap-2 text-xs"><span aria-label={`${r.rating}星，共5星`} className="text-amber-600">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><time className="text-slate-500">{new Date(r.createdAt).toLocaleDateString('zh-CN')}</time></div>{!productId&&<button onClick={()=>onProduct?.(r.productId)} className="mt-2 text-left text-sm font-medium">{r.title}</button>}<p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{r.content}</p><p className="mt-2 text-xs text-slate-500">已购用户 · {r.spec}</p></article>):<p className="py-4 text-sm leading-6 text-slate-500">{productId?'暂无评价，购买并确认收货后可发表真实体验。':'暂无历史评价，已完成的订单可在这里评价。'}</p>}
 {(page>1||more)&&<div className="flex items-center justify-between text-xs"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="min-h-11 px-3 disabled:opacity-40">上一页</button><span>第 {page} 页</span><button disabled={!more} onClick={()=>setPage(p=>p+1)} className="min-h-11 px-3 disabled:opacity-40">下一页</button></div>}</>}
 {edit&&<div className="katu-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="发表商品评价" onSubmit={e=>{e.preventDefault();void submit()}} className="max-h-[85dvh] w-full max-w-sm space-y-4 overflow-y-auto rounded-2xl bg-white p-5"><h3 className="font-semibold">评价：{edit.title}</h3><label className="block text-sm">商品评分<select value={rating} onChange={e=>setRating(Number(e.target.value))} className="mt-2 w-full rounded-xl border bg-transparent p-3">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} 星</option>)}</select></label><label className="block text-sm">购买体验<textarea required minLength={5} maxLength={2000} rows={5} value={content} onChange={e=>setContent(e.target.value)} placeholder="请填写真实使用体验，至少5个字" className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"/></label>{submitError&&<p role="alert" className="text-sm text-red-600">{submitError}</p>}<div className="grid grid-cols-2 gap-3"><button type="button" disabled={busy} onClick={()=>setEdit(null)} className="min-h-11 rounded-full border">取消</button><button disabled={busy} className="min-h-11 rounded-full bg-slate-700 text-white">{busy?'提交中…':'发表评价'}</button></div></form></div>}
 </section>;
}
