"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,MessageCircle,Send} from 'lucide-react';
type Message={context?:Context;id:string;seq:string;content:string;mine:boolean;createdAt:string};
type Context={kind:string;title:string;orderNo?:string;amount?:number};
type Thread={id:string;title:string;preview:string;unread:number;context:Context;updatedAt:string};
async function request(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init}),d=await r.json();if(!r.ok)throw Error(typeof d.message==='string'?d.message:'请求失败，请重试');return d}
export function ContactMerchant({productId,orderId,onOpen,onLogin,className,children}:{productId?:string;orderId?:string;onOpen:(id:string)=>void;onLogin?:()=>void;className?:string;children?:React.ReactNode}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function open(){setBusy(true);setError('');try{const r=await fetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,orderId})}),d=await r.json();if(r.status===401&&onLogin){onLogin();return}if(!r.ok)throw Error(d.message);onOpen(d.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><button type="button" disabled={busy} onClick={()=>void open()} className={className||'min-h-11 rounded-full border px-4 text-xs'}>{busy?'连接中…':children||'联系商家'}</button>{error&&<div role="alert" className="chat-contact-error"><span>{error}</span><button onClick={()=>setError('')}>关闭</button></div>}</>;
}
export function ConversationList({mode='buyer',onOpen,onLogin}:{mode?:'buyer'|'merchant';onOpen:(id:string)=>void;onLogin?:()=>void}){
 const[rows,setRows]=useState<Thread[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;setLoading(true);setRows([]);
 const load=async()=>{try{if(!document.hidden){const d=await request('/api/conversations?mode='+mode+'&page='+page,{signal:controller.signal});if(!controller.signal.aborted){setRows(d.conversations);setMore(d.hasMore);setError('')}}}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}finally{if(!controller.signal.aborted){setLoading(false);timer=setTimeout(load,5000)}}};void load();return()=>{controller.abort();clearTimeout(timer)}},[mode,page,version]);
 return <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{mode==='merchant'?'买家咨询':'商家会话'}</h2><button onClick={()=>setVersion(v=>v+1)} className="min-h-11 px-3 text-xs">刷新</button></div>{error&&<div role="alert" className="rounded-xl bg-white p-4 text-sm">{error}{onLogin&&error.includes('登录')&&<button onClick={onLogin} className="ml-3 min-h-11 underline">去登录</button>}</div>}{loading?<p className="py-5 text-sm">正在加载会话…</p>:!error&&!rows.length?<div className="rounded-2xl bg-white p-6 text-center text-sm leading-6"><MessageCircle className="mx-auto mb-3" size={26}/>{mode==='merchant'?'暂无买家咨询，新消息会自动显示在这里。':'暂无商家会话，可从商品详情或订单点击“联系商家”。'}</div>:rows.map(r=><button key={r.id} onClick={()=>onOpen(r.id)} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left"><MessageCircle className="shrink-0" size={23}/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{r.title}</b><span className="mt-1 block truncate text-xs text-slate-500">{r.context.orderNo?'订单 '+r.context.orderNo:r.context.title}</span><span className="mt-1 block truncate text-xs">{r.preview||'尚未发送消息'}</span></span>{r.unread>0&&<span className="rounded-full bg-red-500 px-2 py-1 text-xs text-white">{r.unread>99?'99+':r.unread}</span>}</button>)}{(more||page>1)&&<div className="flex justify-between text-xs"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="min-h-11 px-3">上一页</button><span className="self-center">{page}</span><button disabled={!more} onClick={()=>setPage(p=>p+1)} className="min-h-11 px-3">下一页</button></div>}</section>;
}
export function ShopConversation({id,onBack,onLogin}:{id:string;onBack:()=>void;onLogin?:()=>void}){
 const[rows,setRows]=useState<Message[]>([]),[title,setTitle]=useState('商家咨询'),[context,setContext]=useState<Context|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[sendError,setSendError]=useState(''),[connection,setConnection]=useState('正在连接…'),[ready,setReady]=useState(false),[canSend,setCanSend]=useState(false),[busy,setBusy]=useState(false),[olderBusy,setOlderBusy]=useState(false),[hasOlder,setHasOlder]=useState(false),[version,setVersion]=useState(0),[peerRead,setPeerRead]=useState('0'),[newCount,setNewCount]=useState(0);
 const list=useRef<HTMLDivElement>(null),tail=useRef('0'),first=useRef(true),nearBottom=useRef(true),pending=useRef<{text:string;nonce:string}|null>(null),acked=useRef('0');
 const scrollBottom=()=>{if(list.current)list.current.scrollTop=list.current.scrollHeight;nearBottom.current=true;setNewCount(0)};
 function merge(messages:Message[]){setRows(old=>Array.from(new Map([...old,...messages].map(m=>[m.id,m])).values()).sort((a,b)=>BigInt(a.seq)<BigInt(b.seq)?-1:1))}
 function ack(seq:string){if(document.hidden||BigInt(seq)<=BigInt(acked.current))return;void request('/api/conversations/'+id+'/messages',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({seq})}).then(()=>{if(BigInt(seq)>BigInt(acked.current))acked.current=seq}).catch(()=>{})}
 useEffect(()=>{let source:EventSource|null=null,stopped=false;const connect=()=>{if(stopped||document.hidden)return;source?.close();setConnection('正在连接…');source=new EventSource('/api/conversations/'+id+'/events?after='+tail.current);
 source.addEventListener('messages',event=>{const d=JSON.parse((event as MessageEvent).data);setConnection('已连接，消息自动更新');setError('');setReady(true);setCanSend(d.canSend);setTitle(d.title);setContext(d.context);setPeerRead(d.peerReadSeq);if(first.current){setHasOlder(d.hasMore);first.current=false}if(d.messages.length){tail.current=d.messages[d.messages.length-1].seq;merge(d.messages);if(nearBottom.current){requestAnimationFrame(scrollBottom);ack(tail.current)}else setNewCount(n=>n+d.messages.length)}});
 source.addEventListener('accessError',event=>{setError(JSON.parse((event as MessageEvent).data).message);setConnection('连接已暂停');source?.close()});source.onerror=()=>{setConnection('连接中断，正在重连…');void request('/api/conversations/'+id+'/messages?after='+tail.current).then(d=>{if(stopped||document.hidden)return;setReady(true);setCanSend(d.canSend);setTitle(d.title);setContext(d.context);setPeerRead(d.peerReadSeq);if(first.current){setHasOlder(d.hasMore);first.current=false}if(d.messages.length){tail.current=d.messages.at(-1).seq;merge(d.messages);if(nearBottom.current){requestAnimationFrame(scrollBottom);ack(tail.current)}}}).catch(e=>{if(!stopped)setError(e.message)})}};
 const visibility=()=>{if(document.hidden){source?.close();source=null}else connect()};connect();document.addEventListener('visibilitychange',visibility);return()=>{stopped=true;source?.close();document.removeEventListener('visibilitychange',visibility)}},[id,version]);
 async function send(){const content=text.trim();if(!content||busy)return;setBusy(true);setSendError('');if(!pending.current||pending.current.text!==content)pending.current={text:content,nonce:crypto.randomUUID()};try{const d=await request('/api/conversations/'+id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,nonce:pending.current.nonce})});merge([d.message]);setText('');pending.current=null;requestAnimationFrame(scrollBottom)}catch(e){setSendError((e as Error).message)}finally{setBusy(false)}}
 async function older(){if(!rows.length||olderBusy)return;setOlderBusy(true);const before=rows[0].seq,oldHeight=list.current?.scrollHeight||0,oldTop=list.current?.scrollTop||0;try{const d=await request('/api/conversations/'+id+'/messages?before='+before);merge(d.messages);setHasOlder(d.hasMore);requestAnimationFrame(()=>{if(list.current)list.current.scrollTop=oldTop+list.current.scrollHeight-oldHeight})}catch(e){setError((e as Error).message)}finally{setOlderBusy(false)}}
 return <section className="shop-chat"><header className="shop-chat-header"><button onClick={onBack} aria-label="返回消息列表"><ArrowLeft size={20}/></button><div><h1>{title}</h1><p>{connection}</p></div><button onClick={()=>setVersion(v=>v+1)} className="text-xs">重连</button></header>{context&&<div className="shop-chat-context"><b>{context.kind==='order'?'订单咨询':'商品咨询'} · {context.title}</b>{context.orderNo&&<p>订单号：{context.orderNo}</p>}{context.amount!=null&&<p>Ks {Number(context.amount).toLocaleString('zh-CN')}</p>}</div>}
 <div ref={list} className="shop-chat-messages" onScroll={()=>{const el=list.current;if(!el)return;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<60;if(nearBottom.current){setNewCount(0);ack(tail.current)}}}>{hasOlder&&<button disabled={olderBusy} onClick={()=>void older()} className="mx-auto block min-h-11 px-4 text-xs">{olderBusy?'加载中…':'查看更早消息'}</button>}{ready&&!rows.length&&<p className="py-8 text-center text-xs text-slate-500">描述你的问题，商家回复后会显示在这里。</p>}{rows.map(m=><div key={m.id} className={'shop-chat-row '+(m.mine?'mine':'')}><p>{m.context&&<span className="mb-2 block border-b pb-2 text-xs opacity-70">{m.context.orderNo?"订单 "+m.context.orderNo:m.context.title}</span>}{m.content}</p><small>{new Date(m.createdAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}{m.mine&&(BigInt(m.seq)<=BigInt(peerRead)?' · 已读':' · 已发送')}</small></div>)}</div>
 {newCount>0&&<button className="min-h-11 text-xs" onClick={()=>{scrollBottom();ack(tail.current)}}>{newCount} 条新消息 ↓</button>}{error&&<p role="alert" className="px-4 py-2 text-xs text-red-600">{error}{onLogin&&error.includes("登录")&&<button onClick={onLogin} className="ml-3 min-h-11 underline">重新登录</button>}</p>}{ready&&!canSend&&<p className="px-4 py-2 text-xs">店铺已暂停营业，历史消息仍可查看。</p>}
 {sendError&&<p role="alert" className="px-4 py-2 text-xs text-red-600">{sendError}，内容已保留，可再次点击发送。</p>}
 <form className="shop-chat-composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="输入咨询消息" placeholder="输入商品或订单问题" maxLength={2000} rows={2} value={text} disabled={busy||ready&&!canSend} onChange={e=>setText(e.target.value)}/><button disabled={!ready||!canSend||!text.trim()||busy} aria-label="发送消息"><Send size={18}/>{busy?'发送中':'发送'}</button></form></section>;
}
