import {catalogQuery} from "../../../lib/catalog-query";
import {NextResponse} from "next/server";import {ensureMerchantSchema} from "../../../lib/merchant";export const dynamic="force-dynamic";
const strings=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[];
function product(r:any){const price=Number(r.price)||0,original=Number(r.originalPrice)||price,images=strings(r.images),rating=Number(r.ratingAverage)||0,sales=Number(r.salesCount)||0;return{merchantId:r.merchantId,rules:r.rules,id:String(r.id),title:String(r.title),subtitle:String(r.subtitle||r.description||"").slice(0,160),description:String(r.description||""),price,original,rating:rating?rating.toFixed(1):"暂无",ratingCount:Number(r.ratingCount)||0,distance:[r.city,r.township].filter(Boolean).join(" · ")||"本地",sales:sales?`已售 ${sales}`:"新品",salesCount:sales,tags:strings(r.tags).slice(0,4),store:String(r.storeNameCn||r.storeNameMm||"卡兔商家"),imageLabel:images.length?"商品图片":"暂无商品图片",images,category:String(r.category||""),stock:Number(r.stock)||0,badge:r.badge||null,isOfficial:!!r.isOfficial,isFeatured:!!r.isFeatured,isRecommended:!!r.isRecommended,promotionTitle:r.promotionTitle||null,specifications:Array.isArray(r.specifications)?r.specifications:[],shippingFee:Number(r.shippingFee)||0,freeShipping:!!r.freeShipping,serviceGuarantees:strings(r.serviceGuarantees)}}
export async function GET(request:Request){let query;try{query=catalogQuery(new URL(request.url).searchParams)}catch(e){return NextResponse.json({products:[],message:(e as Error).message},{status:400})}try{
 const db=await ensureMerchantSchema();
 const [r,count,facets]=await Promise.all([
 db.query(`SELECT p.product_rules AS "rules",p.id,p.title,p.subtitle,p.description,p.category,p.price,p.original_price AS "originalPrice",p.stock,p.images,p.badge,p.tags,p.specifications,p.shipping_fee AS "shippingFee",p.free_shipping AS "freeShipping",p.service_guarantees AS "serviceGuarantees",p.is_official AS "isOfficial",p.is_featured AS "isFeatured",p.is_recommended AS "isRecommended",CASE WHEN (p.promotion_start IS NULL OR p.promotion_start<=NOW()) AND (p.promotion_end IS NULL OR p.promotion_end>=NOW()) THEN p.promotion_title ELSE NULL END AS "promotionTitle",p.sales_count AS "salesCount",p.rating_average AS "ratingAverage",p.rating_count AS "ratingCount",m.id AS "merchantId",m.store_name_cn AS "storeNameCn",m.store_name_mm AS "storeNameMm",m.city,m.township FROM products p JOIN merchants m ON m.id=p.merchant_id WHERE ${query.where} ORDER BY ${query.order} LIMIT $${query.values.length+1} OFFSET $${query.values.length+2}`,[...query.values,query.limit,(query.page-1)*query.limit]),
 db.query(`SELECT count(*)::int AS total FROM products p JOIN merchants m ON m.id=p.merchant_id WHERE ${query.where}`,query.values),
 db.query("SELECT DISTINCT p.category FROM products p JOIN merchants m ON m.id=p.merchant_id WHERE p.status='active' AND p.stock>0 AND m.status='active' ORDER BY p.category")
 ]);
 const products=r.rows.map(product),total=Number(count.rows[0]?.total||0);
 return NextResponse.json(query.id?{product:products[0]||null}:{products,total,page:query.page,pageSize:query.limit,pages:Math.max(1,Math.ceil(total/query.limit)),categories:facets.rows.map(r=>r.category).filter(Boolean)});
}catch(e){console.error(e);return NextResponse.json({products:[],message:"商品加载失败，请稍后重试"},{status:503})}}
