"use client";
import {useEffect,useRef,useState,type TouchEvent} from "react";
import {ArrowLeft,ChevronRight,Minus,Plus,ShoppingCart,Store} from "lucide-react";
import type {CartItem} from "../../lib/data";
import {formatMoney} from "../../lib/data";
import {readCart,saveCart} from "../../lib/cart";
import {SkeletonImage} from "../ui";

function Row({item,selected,onToggle,onDelete,onQuantity}:{item:CartItem;selected:boolean;onToggle:()=>void;onDelete:()=>void;onQuantity:(n:number)=>void}){
 const [open,setOpen]=useState(false);const x=useRef(0);
 const start=(e:TouchEvent)=>{x.current=e.touches[0]?.clientX||0};const end=(e:TouchEvent)=>{const d=x.current-(e.changedTouches[0]?.clientX||x.current);if(d>35)setOpen(true);if(d< -35)setOpen(false)};
 return <div className="relative overflow-hidden bg-white"><button onClick={onDelete} className="absolute inset-y-0 right-0 w-[72px] bg-[#d96f68] text-xs text-white">删除</button><div onTouchStart={start} onTouchEnd={end} style={{transform:open?"translateX(-72px)":"none"}} className="relative flex gap-2.5 bg-white px-3.5 py-3 transition-transform"><input type="checkbox" checked={selected} onChange={onToggle} className="mt-5 size-4 accent-[#7189a1]"/><SkeletonImage className="h-[76px] w-[76px] shrink-0 rounded-xl" label={item.imageLabel}/><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-sm font-semibold text-slate-800">{item.title}</h3><p className="mt-1 text-[11px] text-slate-400">{item.spec}</p><div className="mt-3 flex items-end justify-between"><b className="text-base text-[#d96f68]">{formatMoney(item.unit)}</b><div className="flex items-center overflow-hidden rounded-lg border border-slate-200"><button onClick={()=>onQuantity(-1)} className="flex size-7 items-center justify-center"><Minus size={13}/></button><span className="flex h-7 w-7 items-center justify-center border-x text-xs">{item.quantity}</span><button onClick={()=>onQuantity(1)} className="flex size-7 items-center justify-center"><Plus size={13}/></button></div></div></div></div></div>
}
export function CartPage({onBack,onCheckout}:{onBack:()=>void;onCheckout:(total:number)=>void}){
 const [items,setItems]=useState<CartItem[]>([]),[selected,setSelected]=useState<string[]>([]),[managing,setManaging]=useState(false);
 useEffect(()=>{const v=readCart();setItems(v);setSelected(v.map(x=>x.id))},[]);
 const persist=(v:CartItem[])=>{setItems(v);saveCart(v)};
 const shops=Array.from(new Set(items.map(x=>x.shop))), chosen=items.filter(x=>selected.includes(x.id));
 const count=chosen.reduce((n,x)=>n+x.quantity,0),total=chosen.reduce((n,x)=>n+x.unit*x.quantity,0),all=items.length>0&&selected.length===items.length;
 return <main className="min-h-screen bg-[#f4f6f8] pb-28"><header className="flex items-center justify-between px-4 pb-3 pt-9"><button onClick={onBack} aria-label="返回" className="flex size-9 items-center justify-center rounded-full bg-white shadow-sm"><ArrowLeft size={19}/></button><h1 className="text-[17px] font-bold">购物车</h1><button onClick={()=>setManaging(!managing)} className="text-sm text-slate-500">{managing?"完成":"管理"}</button></header>
 {items.length===0?<section className="mx-4 mt-20 flex flex-col items-center rounded-3xl bg-white px-6 py-12"><ShoppingCart size={42} className="text-slate-300"/><h2 className="mt-4 font-semibold">购物车还是空的</h2><p className="mt-2 text-xs text-slate-400">从商品详情页加入商品后会保存在这里</p></section>:<section className="space-y-3 px-4">{shops.map(shop=>{const si=items.filter(x=>x.shop===shop),sa=si.every(x=>selected.includes(x.id));return <div key={shop} className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="flex items-center gap-2 px-3.5 py-3"><input type="checkbox" checked={sa} onChange={()=>setSelected(c=>sa?c.filter(id=>!si.some(x=>x.id===id)):Array.from(new Set([...c,...si.map(x=>x.id)])))} className="size-4 accent-[#7189a1]"/><Store size={16} className="text-[#7189a1]"/><b className="flex-1 text-sm">{shop}</b><ChevronRight size={16} className="text-slate-300"/></div>{si.map(item=><Row key={item.id} item={item} selected={selected.includes(item.id)} onToggle={()=>setSelected(c=>c.includes(item.id)?c.filter(x=>x!==item.id):[...c,item.id])} onDelete={()=>{persist(items.filter(x=>x.id!==item.id));setSelected(c=>c.filter(x=>x!==item.id))}} onQuantity={n=>persist(items.map(x=>x.id===item.id?{...x,quantity:Math.max(1,x.quantity+n)}:x))}/>)}</div>})}<p className="text-center text-[10px] text-slate-400">商品可左滑删除</p></section>}
 <div className="fixed bottom-0 left-1/2 z-40 flex h-[72px] w-full max-w-[390px] -translate-x-1/2 items-center gap-3 border-t bg-white/95 px-3"><label className="flex items-center gap-1.5 text-xs"><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:items.map(x=>x.id))} className="size-4 accent-[#7189a1]"/>全选</label><div className="min-w-0 flex-1"><small className="block text-slate-400">合计</small><b className="text-lg text-[#d96f68]">{formatMoney(total)}</b></div><button disabled={!count} onClick={()=>onCheckout(total)} className="h-11 rounded-full bg-[#7189a1] px-5 text-xs font-semibold text-white disabled:opacity-40">去结算({count})</button></div></main>
}