"use client";
import {useEffect,useRef,useState} from 'react';
import {Heart,Search,ShoppingCart,SlidersHorizontal,Store,X,PackageOpen,MoreHorizontal,ChevronRight,ArrowDownUp,Plus} from 'lucide-react';
import type {ProductData,View} from '../../lib/data';
import {formatMoney} from '../../lib/data';
import {addProductToCart,readCart} from '../../lib/cart';
import {DELIVERY_REGIONS} from '../../lib/product-rules';
import {useCatalogResource} from '../use-catalog-resource';
import {usePublicViewState} from '../use-public-view-state';
import {SkeletonImage} from '../ui';
type Filters={category:string;section:string;sort:string;minPrice:string;maxPrice:string;freeShipping:boolean;region:string;store:string;storeName:string};
const defaults:Filters={category:'',section:'',sort:'default',minPrice:'',maxPrice:'',freeShipping:false,region:'',store:'',storeName:''};
export function MallPage({onProduct,onNavigate,cartCount}:{onProduct:(id:string)=>void;onNavigate:(view:View)=>void;cartCount:number}){
 const[q,setQ]=usePublicViewState('mall:q',''),[keyword,setKeyword]=usePublicViewState('mall:keyword',''),[filters,setFilters]=usePublicViewState<Filters>('mall:filters',defaults),[page,setPage]=usePublicViewState('mall:page',1);
 const[menuOpen,setMenuOpen]=useState(false),[draft,setDraft]=useState(filters),[filterOpen,setFilterOpen]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0),[favorites,setFavorites]=useState<string[]>([]);
 const input=useRef<HTMLInputElement>(null),results=useRef<HTMLDivElement>(null);
 const params=new URLSearchParams({q:keyword,category:filters.category,section:filters.section,sort:filters.sort,minPrice:filters.minPrice,maxPrice:filters.maxPrice,freeShipping:String(filters.freeShipping),region:filters.region,store:filters.store,page:String(page),limit:'20',refresh:String(retry)});
 const catalog=useCatalogResource('/api/catalog?'+params),products=catalog.data?.products||[],pages=catalog.data?.pages||1,total=catalog.data?.total||0,categories=catalog.data?.categories||[];
 useEffect(()=>{const sync=()=>{try{const v=JSON.parse(localStorage.getItem('katu.favorites')||'[]');setFavorites(Array.isArray(v)?v:[])}catch{setFavorites([])}};sync();window.addEventListener('storage',sync);window.addEventListener('katu:favorites',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('katu:favorites',sync)}},[]);
 useEffect(()=>{if(!catalog.loading&&!catalog.error&&page>pages)setPage(pages)},[catalog.loading,catalog.error,page,pages,setPage]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer)},[notice]);
 function change(patch:Partial<Filters>){setFilters(f=>({...f,...patch}));setPage(1)}
 function favorite(p:ProductData){const next=favorites.includes(p.id)?favorites.filter(id=>id!==p.id):[...favorites,p.id];try{localStorage.setItem('katu.favorites',JSON.stringify(next));setFavorites(next);window.dispatchEvent(new Event('katu:favorites'));setNotice(next.includes(p.id)?'已收藏商品':'已取消收藏')}catch{setNotice('收藏保存失败，请检查浏览器存储设置')}}
 function add(p:ProductData){if(p.specifications?.length){onProduct(p.id);return;}const quantity=readCart().find(x=>x.id===p.id+'::默认规格')?.quantity||0;if(quantity>=Math.min(99,p.stock||0)){setNotice('购物车数量已达到库存或单次购买上限');return;}try{addProductToCart(p,1);setNotice('已加入购物车')}catch{setNotice('购物车保存失败，请重试')}}
 function reset(){setFilters(defaults);setQ('');setKeyword('');setPage(1)}
 const activeCount=[filters.minPrice,filters.maxPrice,filters.region,filters.freeShipping].filter(Boolean).length;
 return <main className="katu-mall min-h-screen pb-28">
 <header className="mall-header"><h1 className="sr-only">商城</h1><div className="mall-search-row"><form onSubmit={e=>{e.preventDefault();setKeyword(q.trim());setPage(1);input.current?.blur()}} className="katu-search-form mall-search"><Search size={17}/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} aria-label="搜索商城商品或店铺" placeholder="搜索你想要的商品" enterKeyHint="search" className="katu-search-input"/>{q&&<button type="button" onClick={()=>{setQ('');setKeyword('');setPage(1)}} aria-label="清空搜索" className="mall-clear"><X size={14}/></button>}<button className="mall-search-submit">搜索</button></form><button onClick={()=>onNavigate('cart')} aria-label={`购物车，${cartCount}件商品`} className="mall-icon-button"><ShoppingCart size={21}/>{cartCount>0&&<span className="mall-cart-badge">{cartCount>99?'99+':cartCount}</span>}</button><button onClick={()=>setMenuOpen(true)} aria-label="商城更多服务" className="mall-icon-button"><MoreHorizontal size={21}/></button></div>
 <nav aria-label="商城分类" className="mall-categories">{['',...categories].map(c=><button key={c} aria-pressed={filters.category===c} onClick={()=>change({category:c})} className={filters.category===c?'selected':''}>{c||'全部'}</button>)}</nav>
 <nav aria-label="商品排序和筛选" className="mall-sort"><button aria-pressed={filters.sort==='default'} onClick={()=>change({sort:'default'})}>综合</button><button aria-pressed={filters.sort==='sales'} onClick={()=>change({sort:'sales'})}>销量</button><button aria-pressed={filters.sort.startsWith('price')} onClick={()=>change({sort:filters.sort==='priceAsc'?'priceDesc':'priceAsc'})}>价格 <ArrowDownUp size={12}/>{filters.sort==='priceAsc'?'↑':filters.sort==='priceDesc'?'↓':''}</button><button onClick={()=>{setDraft(filters);setError('');setFilterOpen(true)}}>筛选 <SlidersHorizontal size={13}/>{activeCount>0&&<i className="mall-filter-dot"/>}</button></nav></header>
 <div className="mall-content" ref={results}>
 {!keyword&&!filters.store&&<div className="mall-discovery"><button aria-pressed={filters.sort==='newest'} onClick={()=>change({sort:filters.sort==='newest'?'default':'newest'})}>最新上架</button><button aria-pressed={filters.section==='sale'} onClick={()=>change({section:filters.section==='sale'?'':'sale'})}>优惠好物</button><button aria-pressed={filters.freeShipping} onClick={()=>change({freeShipping:!filters.freeShipping})}>免运费</button><button aria-pressed={filters.section==='official'} onClick={()=>change({section:filters.section==='official'?'':'official'})}>官方商品</button></div>}
 {filters.store&&<div className="mall-store-heading"><span><Store size={17}/><b>{filters.storeName}</b></span><button onClick={()=>change({store:'',storeName:''})}>全部店铺 <X size={13}/></button></div>}
 {(keyword||filters.region||filters.minPrice||filters.maxPrice||filters.section==='featured')&&<div className="mall-filter-summary"><span>{[keyword?`“${keyword}”`:'',filters.region?`配送至${filters.region}`:'',filters.minPrice||filters.maxPrice?`Ks ${filters.minPrice||'0'}–${filters.maxPrice||'不限'}`:'',filters.section==='featured'?'热门推荐':''].filter(Boolean).join(' · ')}</span><button onClick={reset}>清除</button></div>}
 {catalog.error?<section role="alert" className="mall-empty"><PackageOpen size={32}/><h2>商品暂时没有加载出来</h2><p>请检查网络，再试一次</p><button onClick={()=>setRetry(v=>v+1)}>重新加载</button></section>:catalog.loading?<div aria-busy="true" aria-label="正在加载商品" className="mall-grid">{[1,2,3,4].map(i=><div key={i} className="mall-card mall-skeleton"><div/><span/><span/></div>)}</div>:products.length?<div className="mall-grid">{products.map(p=><article key={p.id} className="mall-card"><div className="mall-photo"><button onClick={()=>onProduct(p.id)} aria-label={`查看${p.title}`}><SkeletonImage src={p.images?.[0]} label={p.title} className="aspect-square w-full"/></button><button onClick={()=>favorite(p)} aria-label={favorites.includes(p.id)?`取消收藏${p.title}`:`收藏${p.title}`} aria-pressed={favorites.includes(p.id)} className="mall-save"><Heart size={16} fill={favorites.includes(p.id)?'currentColor':'none'}/></button></div><div className="mall-card-body"><button onClick={()=>onProduct(p.id)} className="mall-product-link"><h2>{p.isOfficial&&<em className="mall-official">官方</em>}{p.title}</h2></button><div className="mall-benefits">{p.freeShipping&&<span>免运费</span>}{p.promotionTitle?<span className="mall-deal">{p.promotionTitle}</span>:p.original>p.price?<span className="mall-deal">优惠价</span>:null}</div><div className="mall-price-row"><button onClick={()=>onProduct(p.id)} className="mall-price"><small>Ks</small><strong>{p.price.toLocaleString('zh-CN')}</strong>{(p.rules?.variants?.length||0)>1&&<small>起</small>}</button><button onClick={()=>add(p)} aria-label={p.specifications?.length?`选择${p.title}的规格`:`加入购物车：${p.title}`} className="mall-add">{p.specifications?.length?<span>选规格</span>:<Plus size={20}/>}</button></div><div className="mall-meta">{p.original>p.price?<s>Ks {p.original.toLocaleString('zh-CN')}</s>:<span>{p.sales}</span>}{(p.stock||0)<5&&<span>仅剩 {p.stock} 件</span>}</div><button onClick={()=>{change({store:p.merchantId||'',storeName:p.store});window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})}} className="mall-shop"><span>{p.store}</span><ChevronRight size={12}/></button></div></article>)}</div>:<section className="mall-empty"><PackageOpen size={36}/><h2>没有找到合适的商品</h2><p>换个关键词，或放宽筛选条件试试</p><button onClick={reset}>查看全部商品</button></section>}
 {!catalog.loading&&!catalog.error&&products.length>0&&<div className="mall-pagination">{pages>1?<><button disabled={page<=1} onClick={()=>{setPage(page-1);results.current?.scrollIntoView({block:'start'})}}>上一页</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>{setPage(page+1);results.current?.scrollIntoView({block:'start'})}}>下一页</button></>:<span>已展示全部 {total} 件商品</span>}</div>}</div>
 {notice&&<div role="status" className="mall-toast"><span>{notice}</span><button onClick={()=>onNavigate('cart')}>查看购物车</button></div>}
 {menuOpen&&<div className="katu-overlay fixed inset-0 z-50 flex items-end justify-center bg-black/40"><section role="dialog" aria-modal="true" aria-label="商城服务" className="mall-menu"><div><h2>商城服务</h2><button onClick={()=>setMenuOpen(false)} aria-label="关闭商城服务"><X size={20}/></button></div>{([['orders','我的订单'],['favorites','我的收藏'],['addresses','收货地址']] as [View,string][]).map(([v,l])=><button key={v} onClick={()=>{setMenuOpen(false);onNavigate(v)}}>{l}<ChevronRight size={17}/></button>)}</section></div>}
 {filterOpen&&<div className="katu-overlay fixed inset-0 z-50 flex items-end justify-center bg-black/40"><section role="dialog" aria-modal="true" aria-label="商城筛选" className="max-h-[85dvh] w-full max-w-[390px] overflow-y-auto rounded-t-3xl bg-white p-5 pb-[max(20px,env(safe-area-inset-bottom))]"><div className="flex items-center justify-between"><h2 className="font-bold">筛选商品</h2><button onClick={()=>setFilterOpen(false)} aria-label="关闭筛选" className="flex size-11 items-center justify-center"><X size={19}/></button></div>{error&&<p role="alert" className="my-3 text-sm text-red-600">{error}</p>}<label className="mt-3 block text-xs">商品分类<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"><option value="">全部分类</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="mt-3 block text-xs">商品专区<select value={draft.section} onChange={e=>setDraft({...draft,section:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"><option value="">全部商品</option><option value="featured">热门推荐</option><option value="sale">优惠商品</option><option value="official">官方商品</option></select></label><div className="mt-4 grid grid-cols-2 gap-3">{(['minPrice','maxPrice'] as const).map((k,i)=><label key={k} className="text-xs">{i?'最高价（Ks）':'最低价（Ks）'}<input type="number" min="0" inputMode="decimal" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"/></label>)}</div><label className="mt-4 block text-xs">支持配送至<select value={draft.region} onChange={e=>setDraft({...draft,region:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"><option value="">不限地区</option>{DELIVERY_REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={draft.freeShipping} onChange={e=>setDraft({...draft,freeShipping:e.target.checked})}/>只看免运费商品</label><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setDraft({...defaults,store:filters.store,storeName:filters.storeName})} className="min-h-11 rounded-full border text-sm">重置筛选</button><button onClick={()=>{if([draft.minPrice,draft.maxPrice].some(v=>v!==''&&(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>999999999))||draft.minPrice!==''&&draft.maxPrice!==''&&Number(draft.minPrice)>Number(draft.maxPrice)){setError('请填写有效的价格区间');return;}change(draft);setFilterOpen(false)}} className="min-h-11 rounded-full bg-slate-700 text-sm text-white">查看商品</button></div></section></div>}
 </main>;
}
