"use client";
import {useEffect,useRef,useState} from 'react';
import {Heart,Search,ShoppingCart,SlidersHorizontal,Store,X,PackageOpen,RefreshCw} from 'lucide-react';
import type {ProductData,View} from '../../lib/data';
import {formatMoney} from '../../lib/data';
import {addProductToCart,readCart} from '../../lib/cart';
import {DELIVERY_REGIONS} from '../../lib/product-rules';
import {useCatalogResource} from '../use-catalog-resource';
import {usePublicViewState} from '../use-public-view-state';
import {SkeletonImage} from '../ui';
type Filters={category:string;section:string;sort:string;minPrice:string;maxPrice:string;freeShipping:boolean;region:string;store:string;storeName:string};
const defaults:Filters={category:'',section:'',sort:'default',minPrice:'',maxPrice:'',freeShipping:false,region:'',store:'',storeName:''};
export function MallPage({onProduct,onNavigate,cartCount}:{onProduct:(id:string)=>void;onNavigate:(view:View)=>void;cartCount:number}){
 const[q,setQ]=usePublicViewState('mall:q',''),[keyword,setKeyword]=usePublicViewState('mall:keyword',''),[filters,setFilters]=usePublicViewState<Filters>('mall:filters',defaults),[page,setPage]=usePublicViewState('mall:page',1);
 const[draft,setDraft]=useState(filters),[filterOpen,setFilterOpen]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0),[favorites,setFavorites]=useState<string[]>([]);
 const input=useRef<HTMLInputElement>(null),results=useRef<HTMLDivElement>(null);
 const params=new URLSearchParams({q:keyword,category:filters.category,section:filters.section,sort:filters.sort,minPrice:filters.minPrice,maxPrice:filters.maxPrice,freeShipping:String(filters.freeShipping),region:filters.region,store:filters.store,page:String(page),limit:'20',refresh:String(retry)});
 const catalog=useCatalogResource('/api/catalog?'+params),products=catalog.data?.products||[],pages=catalog.data?.pages||1,total=catalog.data?.total||0,categories=catalog.data?.categories||[];
 useEffect(()=>{const sync=()=>{try{const v=JSON.parse(localStorage.getItem('katu.favorites')||'[]');setFavorites(Array.isArray(v)?v:[])}catch{setFavorites([])}};sync();window.addEventListener('storage',sync);window.addEventListener('katu:favorites',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('katu:favorites',sync)}},[]);
 useEffect(()=>{if(!catalog.loading&&!catalog.error&&page>pages)setPage(pages)},[catalog.loading,catalog.error,page,pages,setPage]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer)},[notice]);
 function change(patch:Partial<Filters>){setFilters(f=>({...f,...patch}));setPage(1)}
 function favorite(p:ProductData){const next=favorites.includes(p.id)?favorites.filter(id=>id!==p.id):[...favorites,p.id];try{localStorage.setItem('katu.favorites',JSON.stringify(next));setFavorites(next);window.dispatchEvent(new Event('katu:favorites'));setNotice(next.includes(p.id)?'已收藏商品':'已取消收藏')}catch{setNotice('收藏保存失败，请检查浏览器存储设置')}}
 function add(p:ProductData){if(p.specifications?.length){onProduct(p.id);return;}const quantity=readCart().find(x=>x.id===p.id+'::默认规格')?.quantity||0;if(quantity>=Math.min(99,p.stock||0)){setNotice('购物车数量已达到库存或单次购买上限');return;}try{addProductToCart(p,1);setNotice('已加入购物车')}catch{setNotice('购物车保存失败，请重试')}}
 function reset(){setFilters(defaults);setQ('');setKeyword('');setPage(1)}
 const activeCount=[filters.minPrice,filters.maxPrice,filters.region,filters.freeShipping].filter(Boolean).length;
 return <main className="katu-mall min-h-screen bg-[#f4f6f8] pb-28"><header className="px-4 pb-3 pt-6"><div className="flex items-center justify-between"><div><h1 className="text-lg font-bold">商城</h1><p className="mt-1 text-xs text-slate-500">选好物，逛店铺</p></div><button onClick={()=>onNavigate('cart')} aria-label={`购物车，${cartCount}件商品`} className="relative flex size-11 items-center justify-center rounded-full bg-white"><ShoppingCart size={21}/>{cartCount>0&&<span className="absolute -right-1 -top-1 rounded-full bg-orange-500 px-1.5 text-[10px] text-white">{cartCount>99?'99+':cartCount}</span>}</button></div><form onSubmit={e=>{e.preventDefault();setKeyword(q.trim());setPage(1);input.current?.blur()}} className="katu-search-form mt-4 flex min-h-11 min-w-0 items-center gap-2 rounded-full bg-white px-3"><Search size={17} className="shrink-0 text-slate-400"/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} aria-label="搜索商城商品或店铺" placeholder="搜索商品、分类或店铺" enterKeyHint="search" className="katu-search-input min-w-0 flex-1 bg-transparent py-2 text-base outline-none"/>{q&&<button type="button" onClick={()=>{setQ('');setKeyword('');setPage(1)}} aria-label="清空搜索" className="flex size-9 shrink-0 items-center justify-center"><X size={16}/></button>}<button className="shrink-0 text-sm">搜索</button></form><div className="mt-3 grid grid-cols-4 gap-2">{([['cart','购物车'],['orders','我的订单'],['favorites','我的收藏'],['addresses','收货地址']] as [View,string][]).map(([v,l])=><button key={v} onClick={()=>onNavigate(v)} className="min-h-11 rounded-xl bg-white text-xs">{l}</button>)}</div></header>
 <section className="px-4"><div className="flex gap-2 overflow-x-auto pb-3">{[['','全部商品'],['featured','热门推荐'],['sale','优惠商品'],['official','官方商品']].map(([v,l])=><button key={v} aria-pressed={filters.section===v} onClick={()=>change({section:v})} className={`min-h-11 shrink-0 rounded-full px-4 text-xs ${filters.section===v?'bg-slate-700 text-white':'bg-white text-slate-600'}`}>{l}</button>)}</div><div className="flex gap-2 overflow-x-auto pb-3">{['',...categories].map(c=><button key={c} aria-pressed={filters.category===c} onClick={()=>change({category:c})} className={`min-h-11 shrink-0 rounded-xl border px-3 text-xs ${filters.category===c?'border-orange-400 text-orange-600':'border-transparent text-slate-500'}`}>{c||'全部分类'}</button>)}</div></section>
 <div ref={results} className="px-4"><div className="flex items-center gap-2 rounded-2xl bg-white p-2"><select aria-label="商品排序" value={filters.sort} onChange={e=>change({sort:e.target.value})} className="min-h-11 min-w-0 flex-1 rounded-xl bg-transparent px-2 text-sm"><option value="default">综合排序</option><option value="sales">销量优先</option><option value="newest">最新上架</option><option value="priceAsc">价格从低到高</option><option value="priceDesc">价格从高到低</option></select><button onClick={()=>{setDraft(filters);setError('');setFilterOpen(true)}} className="flex min-h-11 items-center gap-1 rounded-xl px-3 text-xs"><SlidersHorizontal size={16}/>筛选{activeCount>0?`（${activeCount}）`:''}</button><button aria-label="刷新商城" onClick={()=>setRetry(v=>v+1)} className="flex size-11 items-center justify-center"><RefreshCw size={16}/></button></div>{filters.store&&<div className="mt-3 flex items-center justify-between rounded-xl bg-white p-3 text-xs"><span className="flex items-center gap-2"><Store size={16}/>{filters.storeName}</span><button onClick={()=>change({store:'',storeName:''})} className="min-h-11 px-2">查看全商城</button></div>}<div className="flex min-h-11 items-center justify-between gap-2 text-xs text-slate-500"><span>{catalog.loading?'正在加载商品…':`找到 ${total} 件商品`}</span>{(keyword||Object.keys(defaults).some(k=>filters[k as keyof Filters]!==defaults[k as keyof Filters]))&&<button onClick={reset} className="min-h-11">清除条件</button>}</div>
 {catalog.error?<section role="alert" className="rounded-2xl bg-white p-6 text-center"><p className="text-sm">商品加载失败，请重试</p><button onClick={()=>setRetry(v=>v+1)} className="mt-3 min-h-11 rounded-full border px-6 text-sm">重新加载</button></section>:catalog.loading?<div aria-busy="true" className="grid grid-cols-2 gap-3">{[1,2,3,4].map(i=><div key={i} className="h-64 rounded-2xl bg-slate-200"/>)}</div>:products.length?<div className="grid grid-cols-2 gap-3">{products.map(p=><article key={p.id} className="min-w-0 overflow-hidden rounded-2xl bg-white"><div className="relative"><button onClick={()=>onProduct(p.id)} aria-label={`查看${p.title}`} className="block w-full"><SkeletonImage src={p.images?.[0]} label={p.title} className="aspect-square w-full"/></button><button onClick={()=>favorite(p)} aria-label={favorites.includes(p.id)?`取消收藏${p.title}`:`收藏${p.title}`} aria-pressed={favorites.includes(p.id)} className="absolute right-1 top-1 flex size-11 items-center justify-center rounded-full bg-white/90 text-slate-700"><Heart size={18} fill={favorites.includes(p.id)?'currentColor':'none'}/></button></div><div className="p-3"><button onClick={()=>onProduct(p.id)} className="block w-full text-left"><h2 className="line-clamp-2 min-h-10 text-sm font-semibold leading-5">{p.title}</h2><div className="mt-2 flex flex-wrap gap-1 text-[10px] text-slate-500">{p.freeShipping&&<span className="rounded bg-slate-100 px-1.5 py-0.5">免运费</span>}{p.isOfficial&&<span className="rounded bg-slate-100 px-1.5 py-0.5">官方</span>}{p.promotionTitle&&<span className="line-clamp-1 rounded bg-orange-50 px-1.5 py-0.5 text-orange-600">{p.promotionTitle}</span>}</div><p className="mt-2 break-words text-base font-bold text-[#d96f68]">{formatMoney(p.price)}{(p.rules?.variants?.length||0)>1&&<small className="ml-1 font-normal">起</small>}</p>{p.original>p.price&&<s className="text-[10px] text-slate-400">{formatMoney(p.original)}</s>}<p className="mt-1 text-[10px] text-slate-500">{p.sales} · 库存 {p.stock}</p></button><button onClick={()=>{change({store:p.merchantId||'',storeName:p.store});window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})}} className="mt-1 flex min-h-11 w-full items-center gap-1 text-left text-[11px] text-slate-500"><Store size={13} className="shrink-0"/><span className="truncate">{p.store}</span></button><button onClick={()=>add(p)} className="min-h-11 w-full rounded-full bg-[#edf2f5] text-xs font-semibold text-[#607992]">{p.specifications?.length?'选择规格':'加入购物车'}</button></div></article>)}</div>:<section className="flex flex-col items-center rounded-2xl bg-white px-4 py-10 text-center"><PackageOpen size={32} className="text-slate-300"/><h2 className="mt-3 text-sm font-semibold">暂无符合条件的商品</h2><p className="mt-2 text-xs text-slate-500">可调整关键词或筛选条件</p><button onClick={reset} className="mt-3 min-h-11 rounded-full border px-5 text-sm">查看全部商品</button></section>}
 {!catalog.loading&&!catalog.error&&pages>1&&<div className="mt-4 flex items-center justify-between gap-2 text-xs"><button disabled={page<=1} onClick={()=>{setPage(page-1);results.current?.scrollIntoView({block:'start'})}} className="min-h-11 rounded-full border px-4 disabled:opacity-40">上一页</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>{setPage(page+1);results.current?.scrollIntoView({block:'start'})}} className="min-h-11 rounded-full border px-4 disabled:opacity-40">下一页</button></div>}</div>
 {notice&&<div role="status" className="fixed bottom-24 left-1/2 z-40 flex w-[calc(100%-32px)] max-w-[358px] -translate-x-1/2 items-center justify-between gap-2 rounded-2xl bg-slate-800 px-4 py-2 text-xs text-white"><span>{notice}</span><button onClick={()=>onNavigate('cart')} className="min-h-11 shrink-0">查看购物车</button></div>}
 {filterOpen&&<div className="katu-overlay fixed inset-0 z-50 flex items-end justify-center bg-black/40"><section role="dialog" aria-modal="true" aria-label="商城筛选" className="max-h-[85dvh] w-full max-w-[390px] overflow-y-auto rounded-t-3xl bg-white p-5 pb-[max(20px,env(safe-area-inset-bottom))]"><div className="flex items-center justify-between"><h2 className="font-bold">筛选商品</h2><button onClick={()=>setFilterOpen(false)} aria-label="关闭筛选" className="flex size-11 items-center justify-center"><X size={19}/></button></div>{error&&<p role="alert" className="my-3 text-sm text-red-600">{error}</p>}<div className="mt-4 grid grid-cols-2 gap-3">{(['minPrice','maxPrice'] as const).map((k,i)=><label key={k} className="text-xs">{i?'最高价（Ks）':'最低价（Ks）'}<input type="number" min="0" inputMode="decimal" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"/></label>)}</div><label className="mt-4 block text-xs">支持配送至<select value={draft.region} onChange={e=>setDraft({...draft,region:e.target.value})} className="mt-2 w-full rounded-xl border bg-transparent p-3 text-base"><option value="">不限地区</option>{DELIVERY_REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={draft.freeShipping} onChange={e=>setDraft({...draft,freeShipping:e.target.checked})}/>只看免运费商品</label><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setDraft({...draft,minPrice:'',maxPrice:'',region:'',freeShipping:false})} className="min-h-11 rounded-full border text-sm">重置筛选</button><button onClick={()=>{if([draft.minPrice,draft.maxPrice].some(v=>v!==''&&(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>999999999))||draft.minPrice!==''&&draft.maxPrice!==''&&Number(draft.minPrice)>Number(draft.maxPrice)){setError('请填写有效的价格区间');return;}change(draft);setFilterOpen(false)}} className="min-h-11 rounded-full bg-slate-700 text-sm text-white">查看商品</button></div></section></div>}
 </main>;
}
