"use client";
import {useEffect,useState} from 'react';
import {ConversationList} from '../shop-chat';
type Notification={id:string;title:string;content:string;readAt:string|null;createdAt:string};
export function MessagesPage({onOpen,onLogin}:{onOpen:(id:string)=>void;onLogin:()=>void}){
 const[tab,setTab]=useState('chats'),[rows,setRows]=useState<Notification[]>([]),[error,setError]=useState(''),[version,setVersion]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{if(tab!=='notifications')return;const controller=new AbortController();setLoading(true);setError('');fetch('/api/messages',{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);return d}).then(d=>{if(!controller.signal.aborted)setRows(d.messages)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[tab,version]);
 async function read(id?:string){try{const r=await fetch('/api/messages',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{id}:{all:true})});if(!r.ok)throw Error('标记已读失败，请重试');setRows(old=>old.map(m=>!id||m.id===id?{...m,readAt:new Date().toISOString()}:m));setError('')}catch(e){setError((e as Error).message)}}
 return <main className="min-h-screen px-4 pb-28 pt-6"><h1 className="text-xl font-bold">消息</h1><nav className="my-4 flex gap-2">{[['chats','商家咨询'],['notifications','系统通知']].map(([v,label])=><button key={v} aria-pressed={tab===v} onClick={()=>setTab(v)} className={'min-h-11 flex-1 rounded-full border text-sm '+(tab===v?'bg-slate-700 text-white':'bg-white')}>{label}</button>)}</nav>{tab==='chats'?<ConversationList onOpen={onOpen} onLogin={onLogin}/>:<section className="space-y-3"><div className="flex justify-between text-xs"><button onClick={()=>void read()} className="min-h-11 px-3">全部已读</button><button onClick={()=>setVersion(v=>v+1)} className="min-h-11 px-3">刷新</button></div>{error&&<p role="alert" className="rounded-xl bg-white p-4 text-sm">{error}{error.includes('登录')&&<button onClick={onLogin} className="ml-3 underline">去登录</button>}</p>}{loading?<p className="py-6 text-center text-sm">正在加载通知…</p>:!error&&!rows.length?<p className="rounded-2xl bg-white p-8 text-center text-sm">暂无系统通知</p>:rows.map(m=><button key={m.id} onClick={()=>void read(m.id)} className="block w-full rounded-2xl bg-white p-4 text-left"><b className="text-sm">{!m.readAt&&'● '}{m.title}</b><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-6">{m.content}</p><time className="mt-2 block text-xs text-slate-500">{new Date(m.createdAt).toLocaleString('zh-CN')}</time></button>)}</section>}</main>;
}
