"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, PackageOpen, RefreshCw } from "lucide-react";
import { formatMoney } from "../../lib/data";
import { orderLabels } from "../../lib/order-rules";
type Order = { id:string; orderNo:string; status:string; paymentStatus:string; totalAmount:string; items:{title:string;spec:string;quantity:number}[]; createdAt:string; shippingName:string; shippingPhone:string; shippingAddress:string };
export function OrdersPage({onBack}:{onBack:()=>void}) {
  const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[filter,setFilter]=useState("all"),[candidate,setCandidate]=useState<{order:Order;action:string}|null>(null);
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/orders",{cache:"no-store",credentials:"include"}),d=await r.json();if(!r.ok)throw new Error(d.message);setOrders(d.orders||[])}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function update(){if(!candidate)return;setBusy(candidate.order.id);setError("");try{const r=await fetch(`/api/orders/${candidate.order.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:candidate.action})}),d=await r.json();if(!r.ok)throw new Error(d.message);setCandidate(null);await load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy("")}}
  const visible=orders.filter(o=>filter==="all"||(filter==="unpaid"?o.paymentStatus==="unpaid"&&o.status!=="cancelled":filter==="active"?["paid","processing","shipped"].includes(o.status):o.status===filter));
  return <main className="min-h-screen bg-[#f4f6f8] pb-8"><header className="flex items-center px-4 pb-3 pt-9"><button onClick={onBack} aria-label="返回" className="flex size-9 items-center justify-center rounded-full bg-white"><ArrowLeft size={19}/></button><h1 className="flex-1 text-center font-bold">我的订单</h1><button onClick={()=>void load()} disabled={loading} aria-label="刷新订单" className="p-2"><RefreshCw size={18}/></button></header>
  <nav className="flex gap-2 overflow-x-auto px-4 pb-3">{[["all","全部"],["unpaid","待付款"],["active","进行中"],["completed","已完成"],["cancelled","已取消"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`shrink-0 rounded-full border px-3 py-2 text-xs ${filter===v?"bg-[#7189a1] text-white":"bg-white"}`}>{l}</button>)}</nav>
  {error&&<p role="alert" className="m-4 rounded-2xl bg-red-50 p-4 text-sm text-red-600">{error}</p>}
  {loading?<div className="space-y-3 p-4">{[1,2,3].map(x=><div key={x} className="h-32 animate-pulse rounded-3xl bg-slate-200"/>)}</div>:visible.length?<section className="space-y-3 p-4">{visible.map(o=><article key={o.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><span><small className="block text-slate-400">订单号</small><b className="mt-1 block break-all text-xs">{o.orderNo}</b></span><b className="shrink-0 text-xs text-[#607992]">{orderLabels[o.status]||o.status}</b></div><div className="mt-3 space-y-2 border-y py-3">{Array.isArray(o.items)&&o.items.map((x,i)=><div key={i} className="flex justify-between gap-3 text-xs"><span>{x.title} · {x.spec}</span><span className="shrink-0">×{x.quantity}</span></div>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">{o.shippingName} · {o.shippingPhone}<br/>{o.shippingAddress}</p><div className="mt-3 flex justify-between gap-2"><small className="text-slate-400">{new Date(o.createdAt).toLocaleString("zh-CN")}</small><b className="shrink-0 text-[#d96f68]">{formatMoney(Number(o.totalAmount))}</b></div>{o.status==="pending"&&o.paymentStatus==="unpaid"&&<><p className="mt-3 text-xs leading-5 text-slate-500">在线支付尚未开通，当前订单未付款。可取消订单，库存会自动返还。</p><button disabled={!!busy} onClick={()=>setCandidate({order:o,action:"cancel"})} className="mt-3 rounded-full border px-4 py-2 text-xs">取消订单</button></>}{o.status==="shipped"&&o.paymentStatus==="paid"&&<button disabled={!!busy} onClick={()=>setCandidate({order:o,action:"complete"})} className="mt-3 rounded-full bg-[#7189a1] px-4 py-2 text-xs text-white">确认收货 / 服务完成</button>}</article>)}</section>:!error&&<section className="mx-4 mt-16 flex flex-col items-center rounded-3xl bg-white py-12"><PackageOpen size={36} className="text-slate-300"/><b className="mt-4 text-sm">暂无此类订单</b><button onClick={onBack} className="mt-4 text-sm text-[#607992]">返回逛逛</button></section>}
  {candidate&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-6"><section role="dialog" aria-modal="true" aria-labelledby="order-confirm-title" className="w-full max-w-sm rounded-3xl bg-white p-6"><h2 id="order-confirm-title" className="font-bold">{candidate.action==="cancel"?"确认取消订单？":"确认已收到商品或完成服务？"}</h2><p className="mt-3 text-sm text-slate-500">{candidate.action==="cancel"?"取消后将返还库存，需要时可重新下单。":"请在实际收到商品或完成服务后确认。"}</p><div className="mt-5 flex gap-3"><button disabled={!!busy} onClick={()=>setCandidate(null)} className="flex-1 rounded-full border py-3 text-sm">再想想</button><button disabled={!!busy} onClick={()=>void update()} className="flex-1 rounded-full bg-[#7189a1] py-3 text-sm text-white">{busy?"处理中…":"确认"}</button></div></section></div>}
  </main>;
}
