"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,BadgeCheck,Headphones,Heart,Minus,PackageOpen,Plus,Share2,ShieldCheck,Star,Store,Truck} from "lucide-react";
import type {ProductData} from "../../lib/data";import {formatMoney} from "../../lib/data";import {addProductToCart} from "../../lib/cart";import {SkeletonImage} from "../ui";
export function ProductPage({productId,onBack,onAddToCart,onBuy}:{productId:string;onBack:()=>void;onAddToCart:(quantity:number)=>void;onBuy:(total:number)=>void}){
 const [product,setProduct]=useState<ProductData|null>(null),[loading,setLoading]=useState(true),[quantity,setQuantity]=useState(1),[saved,setSaved]=useState(false),[added,setAdded]=useState(false),[selectedSpecs,setSelectedSpecs]=useState<Record<string,string>>({}),[notice,setNotice]=useState("");
 useEffect(()=>{let active=true;setLoading(true);fetch("/api/catalog?id="+encodeURIComponent(productId),{cache:"no-store"}).then(r=>r.json()).then(x=>active&&setProduct(x.product||null)).catch(()=>active&&setProduct(null)).finally(()=>active&&setLoading(false));return()=>{active=false}},[productId]);
 useEffect(()=>{try{const ids=JSON.parse(localStorage.getItem("katu.favorites")||"[]");setSaved(Array.isArray(ids)&&ids.includes(productId))}catch{}},[productId]);
 const toggleSaved=()=>{const next=!saved;setSaved(next);try{const ids=JSON.parse(localStorage.getItem("katu.favorites")||"[]") as string[];localStorage.setItem("katu.favorites",JSON.stringify(next?Array.from(new Set([...ids,productId])):ids.filter(x=>x!==productId)))}catch{}};
 const share=async()=>{const data={title:product?.title||"卡兔商品",url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);setNotice("商品链接已复制")}}catch{}};
 if(loading)return <main className="min-h-screen bg-[#f4f6f8]"><SkeletonImage className="h-[330px] rounded-none" label="正在加载商品"/></main>;
 if(!product)return <main className="min-h-screen bg-[#f4f6f8] px-4"><header className="pt-9"><button onClick={onBack} className="flex size-9 items-center justify-center rounded-full bg-white"><ArrowLeft size={19}/></button></header><section className="mt-20 flex flex-col items-center rounded-3xl bg-white py-12"><PackageOpen size={38} className="text-slate-300"/><h2 className="mt-4 font-semibold">商品已下架或不存在</h2><button onClick={onBack} className="mt-6 rounded-full bg-[#7189a1] px-6 py-3 text-sm text-white">返回</button></section></main>;
 return <main className="min-h-screen bg-[#f4f6f8] pb-24"><section className="relative"><SkeletonImage className="h-[330px] rounded-none" label={product.imageLabel}/><button onClick={onBack} aria-label="返回" className="absolute left-4 top-10 flex size-10 items-center justify-center rounded-full bg-black/25 text-white"><ArrowLeft size={20}/></button><button onClick={share} aria-label="分享" className="absolute right-4 top-10 flex size-10 items-center justify-center rounded-full bg-black/25 text-white"><Share2 size={19}/></button></section><div className="space-y-3 p-4">
 <section className="rounded-3xl bg-white p-4"><div className="flex flex-wrap items-center gap-2">{product.isOfficial&&<span className="rounded-full bg-[#e8eef2] px-2.5 py-1 text-[10px] text-[#607992]">官方认证</span>}{product.badge&&<span className="rounded-full bg-[#f8eae5] px-2.5 py-1 text-[10px] text-[#b47763]">{product.badge}</span>}{product.promotionTitle&&<span className="text-xs text-[#b47763]">{product.promotionTitle}</span>}</div><div className="mt-3 flex items-end gap-2"><b className="text-3xl text-[#d96f68]">{formatMoney(product.price)}</b>{product.original>product.price&&<s className="text-sm text-slate-400">{formatMoney(product.original)}</s>}</div><h1 className="mt-3 text-lg font-bold leading-7">{product.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{product.subtitle||product.description}</p><div className="mt-3 flex gap-3 text-xs text-slate-400"><span className="flex items-center gap-1"><Star size={13}/>{product.rating}</span><span>{product.sales}</span><span>{product.distance}</span></div></section>
 <section className="rounded-3xl bg-white px-4 py-4 text-xs text-slate-600"><div className="flex justify-between"><span className="flex gap-1"><Truck size={16}/>{product.freeShipping?"免运费":`运费 ${formatMoney(product.shippingFee||0)}`}</span><span className="flex gap-1"><ShieldCheck size={16}/>平台商家</span><span className="flex gap-1"><BadgeCheck size={16}/>售后保障</span></div>{product.serviceGuarantees?.length?<div className="mt-3 flex flex-wrap gap-2">{product.serviceGuarantees.map(x=><span key={x} className="rounded-full bg-slate-50 px-2 py-1">{x}</span>)}</div>:null}</section>
 <section className="rounded-3xl bg-white p-4">{product.specifications?.map(spec=><div key={spec.name} className="mb-4"><b className="text-sm">{spec.name}</b><div className="mt-2 flex flex-wrap gap-2">{spec.values.map(value=><button key={value} onClick={()=>setSelectedSpecs({...selectedSpecs,[spec.name]:value})} className={`rounded-xl border px-3 py-2 text-xs ${selectedSpecs[spec.name]===value?"border-[#7189a1] bg-[#edf2f5] text-[#607992]":"border-slate-200"}`}>{value}</button>)}</div></div>)}<div className="flex items-center justify-between"><span><b className="text-sm">购买数量</b><small className="ml-2 text-slate-400">库存 {product.stock}</small></span><div className="flex overflow-hidden rounded-xl border"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} className="flex size-9 items-center justify-center"><Minus size={14}/></button><span className="flex w-10 items-center justify-center border-x text-sm">{quantity}</span><button onClick={()=>setQuantity(Math.min(product.stock||1,quantity+1))} className="flex size-9 items-center justify-center"><Plus size={14}/></button></div></div></section>
 <section className="rounded-3xl bg-white p-4"><b className="text-sm">店铺信息</b><div className="mt-3 flex items-center gap-3"><span className="flex size-12 items-center justify-center rounded-2xl bg-[#edf2f5] text-[#7189a1]"><Store size={21}/></span><div><b className="text-sm">{product.store}</b><p className="mt-1 text-xs text-slate-400">{product.distance}</p></div></div></section>
 <section className="rounded-3xl bg-white p-4"><b className="text-sm">商品详情</b><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{product.description||product.subtitle}</p></section></div>{notice&&<button onClick={()=>setNotice("")} className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2 rounded-full bg-slate-800 px-4 py-2 text-xs text-white">{notice}</button>}
 <footer className="fixed bottom-0 left-1/2 z-40 flex h-[72px] w-full max-w-[390px] -translate-x-1/2 items-center gap-2 border-t bg-white px-3"><button onClick={()=>location.assign("mailto:support@mmkatu.com?subject="+encodeURIComponent("卡兔商品咨询："+product.title))} aria-label="客服" className="flex flex-col items-center px-2 text-[10px] text-slate-500"><Headphones size={19}/>客服</button><button onClick={toggleSaved} className={`flex flex-col items-center px-2 text-[10px] ${saved?"text-[#d96f68]":"text-slate-500"}`}><Heart size={19} fill={saved?"currentColor":"none"}/>收藏</button><button onClick={()=>{addProductToCart(product,quantity,Object.entries(selectedSpecs).map(([k,v])=>`${k}：${v}`).join("；")||"默认规格");onAddToCart(quantity);setAdded(true)}} className="h-11 flex-1 rounded-full bg-[#edf2f5] text-xs font-semibold text-[#647e97]">{added?"已加入":"加入购物车"}</button><button onClick={()=>onBuy(product.price*quantity)} className="h-11 flex-1 rounded-full bg-[#7189a1] text-xs font-semibold text-white">立即购买</button></footer></main>
}