"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,BadgeCheck,Headphones,Heart,Minus,PackageOpen,Plus,Share2,ShieldCheck,Star,Store,Truck} from "lucide-react";
import type {ProductData} from "../../lib/data";import {formatMoney} from "../../lib/data";import {addProductToCart} from "../../lib/cart";import {SkeletonImage} from "../ui";
export function ProductPage({productId,onBack,onAddToCart,onBuy}:{productId:string;onBack:()=>void;onAddToCart:(quantity:number)=>void;onBuy:(total:number)=>void}){
 const [product,setProduct]=useState<ProductData|null>(null),[loading,setLoading]=useState(true),[quantity,setQuantity]=useState(1),[saved,setSaved]=useState(false),[added,setAdded]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);fetch("/api/catalog?id="+encodeURIComponent(productId),{cache:"no-store"}).then(r=>r.json()).then(x=>active&&setProduct(x.product||null)).catch(()=>active&&setProduct(null)).finally(()=>active&&setLoading(false));return()=>{active=false}},[productId]);
 const share=async()=>{const data={title:product?.title||"卡兔商品",url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);alert("链接已复制")}}catch{}};
 if(loading)return <main className="min-h-screen bg-[#f4f6f8]"><SkeletonImage className="h-[330px] rounded-none" label="正在加载商品"/></main>;
 if(!product)return <main className="min-h-screen bg-[#f4f6f8] px-4"><header className="pt-9"><button onClick={onBack} className="flex size-9 items-center justify-center rounded-full bg-white"><ArrowLeft size={19}/></button></header><section className="mt-20 flex flex-col items-center rounded-3xl bg-white py-12"><PackageOpen size={38} className="text-slate-300"/><h2 className="mt-4 font-semibold">商品已下架或不存在</h2><button onClick={onBack} className="mt-6 rounded-full bg-[#7189a1] px-6 py-3 text-sm text-white">返回</button></section></main>;
 return <main className="min-h-screen bg-[#f4f6f8] pb-24"><section className="relative"><SkeletonImage className="h-[330px] rounded-none" label={product.imageLabel}/><button onClick={onBack} aria-label="返回" className="absolute left-4 top-10 flex size-10 items-center justify-center rounded-full bg-black/25 text-white"><ArrowLeft size={20}/></button><button onClick={share} aria-label="分享" className="absolute right-4 top-10 flex size-10 items-center justify-center rounded-full bg-black/25 text-white"><Share2 size={19}/></button></section><div className="space-y-3 p-4">
 <section className="rounded-3xl bg-white p-4"><div className="flex items-end gap-2"><b className="text-3xl text-[#d96f68]">{formatMoney(product.price)}</b>{product.original>product.price&&<s className="text-sm text-slate-400">{formatMoney(product.original)}</s>}</div><h1 className="mt-3 text-lg font-bold leading-7">{product.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{product.subtitle||product.description}</p><div className="mt-3 flex gap-3 text-xs text-slate-400"><span className="flex items-center gap-1"><Star size={13}/>{product.rating}</span><span>{product.sales}</span><span>{product.distance}</span></div></section>
 <section className="flex justify-between rounded-3xl bg-white px-4 py-4 text-xs text-slate-600"><span className="flex gap-1"><Truck size={16}/>配送说明</span><span className="flex gap-1"><ShieldCheck size={16}/>平台商家</span><span className="flex gap-1"><BadgeCheck size={16}/>售后保障</span></section>
 <section className="rounded-3xl bg-white p-4"><div className="flex items-center justify-between"><b className="text-sm">购买数量</b><div className="flex overflow-hidden rounded-xl border"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} className="flex size-9 items-center justify-center"><Minus size={14}/></button><span className="flex w-10 items-center justify-center border-x text-sm">{quantity}</span><button onClick={()=>setQuantity(quantity+1)} className="flex size-9 items-center justify-center"><Plus size={14}/></button></div></div></section>
 <section className="rounded-3xl bg-white p-4"><b className="text-sm">店铺信息</b><div className="mt-3 flex items-center gap-3"><span className="flex size-12 items-center justify-center rounded-2xl bg-[#edf2f5] text-[#7189a1]"><Store size={21}/></span><div><b className="text-sm">{product.store}</b><p className="mt-1 text-xs text-slate-400">{product.distance}</p></div></div></section>
 <section className="rounded-3xl bg-white p-4"><b className="text-sm">商品详情</b><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{product.description||product.subtitle}</p></section></div>
 <footer className="fixed bottom-0 left-1/2 z-40 flex h-[72px] w-full max-w-[390px] -translate-x-1/2 items-center gap-2 border-t bg-white px-3"><button aria-label="客服" className="flex flex-col items-center px-2 text-[10px] text-slate-500"><Headphones size={19}/>客服</button><button onClick={()=>setSaved(!saved)} className={`flex flex-col items-center px-2 text-[10px] ${saved?"text-[#d96f68]":"text-slate-500"}`}><Heart size={19} fill={saved?"currentColor":"none"}/>收藏</button><button onClick={()=>{addProductToCart(product,quantity);onAddToCart(quantity);setAdded(true)}} className="h-11 flex-1 rounded-full bg-[#edf2f5] text-xs font-semibold text-[#647e97]">{added?"已加入":"加入购物车"}</button><button onClick={()=>onBuy(product.price*quantity)} className="h-11 flex-1 rounded-full bg-[#7189a1] text-xs font-semibold text-white">立即购买</button></footer></main>
}