"use client";
import { useState } from "react";
import { Bookmark, ChevronRight, CreditCard, Headphones, Heart, LogOut, Mail, MapPin, Package, Settings, ShieldCheck, Star, Store, Truck, UserRound, X } from "lucide-react";
import type { AuthUser, View } from "../../lib/data";
import { IconListRow, SkeletonImage } from "../ui";
type Panel="support"|"about"|null;
export function ProfilePage({onNavigate,onLogout,user}:{onNavigate:(v:View)=>void;onLogout:()=>void;user:AuthUser|null}){
 const orders=[{label:"待付款",icon:CreditCard},{label:"待发货",icon:Package},{label:"配送中",icon:Truck},{label:"待评价",icon:Star}];
 const [panel,setPanel]=useState<Panel>(null);
 return <main className="min-h-screen overflow-hidden bg-[#eef2f5] pb-28"><section className="relative overflow-hidden bg-[#6f86a1] px-5 pb-16 pt-9 text-white"><div className="absolute -right-12 -top-12 size-40 rounded-full bg-white/10"/><div className="relative flex items-start justify-between"><button type="button" onClick={()=>!user&&onNavigate("login")} className="flex items-center gap-3 text-left"><SkeletonImage className="size-16 rounded-full border-2 border-white/55" compact/><span><b className="block text-lg">{user?user.displayName:"登录 / 注册"}</b><span className="mt-1 block text-xs text-white/70">{user?`账号：${user.username}`:"登录后享受更多权益"}</span></span></button><button type="button" onClick={()=>onNavigate("settings")} aria-label="账户设置" className="flex size-9 items-center justify-center rounded-full bg-white/12"><Settings size={19}/></button></div></section>
 <div className="-mt-9 space-y-3 px-4"><section className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex justify-between"><b>我的订单</b><button type="button" onClick={()=>user?onNavigate("orders"):onNavigate("login")} className="flex items-center text-xs text-slate-400">查看全部<ChevronRight size={14}/></button></div><div className="mt-5 grid grid-cols-4">{orders.map(({label,icon:Icon})=><button type="button" key={label} onClick={()=>user?onNavigate("orders"):onNavigate("login")} className="flex flex-col items-center gap-2 text-xs text-slate-600"><Icon size={21} className="text-[#7189a1]"/>{label}</button>)}</div></section>
 <section className="grid grid-cols-2 gap-3"><button onClick={()=>onNavigate("likes")} className="rounded-3xl bg-white p-4 text-left shadow-sm"><Heart size={20} className="text-[#d68178]"/><p className="mt-3 text-xs text-slate-400">我的点赞</p><b className="mt-1 block text-xl">查看内容</b></button><button onClick={()=>onNavigate("favorites")} className="rounded-3xl bg-white p-4 text-left shadow-sm"><Bookmark size={20} className="text-[#7189a1]"/><p className="mt-3 text-xs text-slate-400">我的收藏</p><b className="mt-1 block text-xl">查看</b></button></section>
 {(!user||user.role==="user")&&<button type="button" onClick={()=>onNavigate("merchantApply")} className="flex w-full items-center justify-between rounded-3xl bg-[#e7edf1] p-4 text-left"><span className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-white/70 text-[#6e879e]"><Store size={22}/></span><span><b className="block text-sm text-slate-700">商家入驻申请</b><span className="mt-1 block text-[11px] text-slate-500">提交经营资料，审核通过后开通</span></span></span><ChevronRight size={18}/></button>}
 {user?.role==="merchant"&&<button type="button" onClick={()=>window.location.assign("/merchant")} className="flex w-full items-center justify-between rounded-3xl bg-[#e7edf1] p-4 text-left"><b>商家后台</b><ChevronRight size={18}/></button>}
 <section className="overflow-hidden rounded-3xl bg-white shadow-sm"><IconListRow icon={MapPin} label="地址管理" onClick={()=>onNavigate("addresses")}/><IconListRow icon={Headphones} label="官方客服" onClick={()=>setPanel("support")}/><IconListRow icon={UserRound} label="关于我们" onClick={()=>setPanel("about")} divider={false}/>{user?.role==="admin"&&<IconListRow icon={ShieldCheck} label="管理后台" onClick={()=>window.location.assign("/admin")}/>} {user&&<IconListRow icon={LogOut} label="退出登录" onClick={onLogout} divider={false}/>}</section></div>
 {panel&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/35 p-3"><section className="katu-glass-strong w-full max-w-[390px] rounded-3xl p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{panel==="support"?"官方客服":"关于卡兔"}</h2><button onClick={()=>setPanel(null)} className="flex size-9 items-center justify-center rounded-full bg-white/60"><X size={17}/></button></div>{panel==="support"?<div className="mt-5 space-y-3"><p className="text-sm leading-6 text-slate-500">遇到订单、商家或账号问题，请通过官方邮箱联系我们。</p><a href="mailto:support@mmkatu.com" className="flex items-center gap-2 rounded-2xl bg-white/50 p-4 text-sm text-[#607992]"><Mail size={18}/>support@mmkatu.com</a></div>:<div className="mt-5 text-sm leading-7 text-slate-500"><p>卡兔是面向缅甸华人的本地生活与电商服务平台。</p><p className="mt-3 text-xs text-slate-400">当前版本 1.0.0</p></div>}</section></div>}</main>;
}
