"use client";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, CalendarDays, CarFront, ChevronRight, Clock3, Coffee, Filter, Hotel, MapPin, Minus, Navigation, PackageCheck, Plane, Plus, Search, ShieldCheck, ShoppingBag, ShoppingBasket, Star, Store, Users, WalletCards, X, Zap } from "lucide-react";
import type { ProductData } from "../../lib/data";
import { formatMoney } from "../../lib/data";
import { addProductToCart } from "../../lib/cart";
import { SkeletonImage } from "../ui";

type Props={title?:string;onBack:()=>void;onProduct:(id:string)=>void;onService?:(name:string)=>void};
type CatalogProps={title:string;onBack:()=>void;onProduct:(id:string)=>void};

function Shell({title,onBack,children,dark=false}:{title:string;onBack:()=>void;children:ReactNode;dark?:boolean}){
 return <main className={dark?"min-h-screen bg-[#17232d] text-white":"min-h-screen bg-[#f5f7f9] text-slate-800"}><header className={`sticky top-0 z-20 flex items-center border-b px-4 py-3 backdrop-blur ${dark?"border-white/10 bg-[#17232d]/95":"border-slate-100 bg-white/95"}`}><button onClick={onBack} aria-label="返回" className={`flex size-10 items-center justify-center rounded-full ${dark?"bg-white/10":"bg-slate-50"}`}><ArrowLeft size={20}/></button><h1 className="flex-1 pr-10 text-center font-bold">{title}</h1></header>{children}</main>
}
function useCatalog(title:string){
 const [query,setQuery]=useState(""),[items,setItems]=useState<ProductData[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);fetch("/api/catalog?q="+encodeURIComponent(query.trim()||title),{cache:"no-store"}).then(r=>r.json()).then(x=>active&&setItems(x.products||[])).catch(()=>active&&setItems([])).finally(()=>active&&setLoading(false));return()=>{active=false}},[query,title]);
 return {query,setQuery,items,loading};
}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){
 return <div className="flex items-center rounded-full bg-white px-3 py-3 text-slate-500 shadow-sm"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="ml-2 min-w-0 flex-1 bg-transparent text-sm outline-none"/>{value&&<button onClick={()=>onChange("")} aria-label="清空"><X size={16}/></button>}</div>
}
function Empty({name}:{name:string}){return <section className="mx-4 mt-10 rounded-3xl bg-white px-5 py-12 text-center"><ShoppingBag size={34} className="mx-auto text-slate-300"/><b className="mt-4 block text-sm">暂无已上架{name}</b><p className="mt-2 text-xs text-slate-400">商家发布并通过平台审核后会显示在这里</p></section>}
function Loading({grid=false}:{grid?:boolean}){return <div className={grid?"grid grid-cols-2 gap-3 px-4":"space-y-3 px-4"}>{[1,2,3,4].map(x=><div key={x} className="h-36 animate-pulse rounded-3xl bg-slate-200"/>)}</div>}
function add(item:ProductData){addProductToCart(item,1,"默认规格");window.dispatchEvent(new Event("katu:cart"))}

function FoodPage({title,onBack,onProduct}:CatalogProps){
 const {query,setQuery,items,loading}=useCatalog(title); const [tab,setTab]=useState("推荐"); const tabs=["推荐","附近","热销","优惠"];
 return <Shell title="外卖" onBack={onBack}><section className="bg-[#7189a1] px-4 pb-6 pt-4"><SearchBox value={query} onChange={setQuery} placeholder="搜索餐厅、菜品"/></section><div className="flex gap-2 overflow-x-auto px-4 py-4">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`shrink-0 rounded-full px-4 py-2 text-xs ${tab===x?"bg-[#7189a1] text-white":"bg-white text-slate-500"}`}>{x}</button>)}</div>{loading?<Loading/>:items.length?<section className="space-y-3 px-4 pb-8">{items.map(p=><article key={p.id} className="rounded-3xl bg-white p-3 shadow-sm"><button onClick={()=>onProduct(p.id)} className="flex w-full gap-3 text-left"><SkeletonImage className="size-24 shrink-0 rounded-2xl" label={p.imageLabel}/><span className="min-w-0 flex-1"><span className="flex items-center gap-1"><b className="truncate text-sm">{p.store}</b>{p.isOfficial&&<small className="rounded bg-[#e8eef2] px-1.5 py-0.5 text-[#607992]">认证</small>}</span><strong className="mt-2 line-clamp-2 block text-sm">{p.title}</strong><span className="mt-2 flex gap-2 text-[11px] text-slate-400"><span className="flex items-center gap-1"><Star size={12}/>{p.rating}</span><span>{p.sales}</span><span>{p.distance}</span></span></span></button><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><b className="text-lg text-[#d96f68]">{formatMoney(p.price)}</b><button onClick={()=>add(p)} className="flex size-9 items-center justify-center rounded-full bg-[#7189a1] text-white" aria-label="加入购物车"><Plus size={17}/></button></div></article>)}</section>:<Empty name="外卖餐品"/>}</Shell>
}
function HotelPage({title,onBack,onProduct}:CatalogProps){
 const {query,setQuery,items,loading}=useCatalog(title);const today=new Date().toISOString().slice(0,10);const [checkIn,setCheckIn]=useState(today),[nights,setNights]=useState(1),[guests,setGuests]=useState(2);
 return <Shell title="酒店" onBack={onBack}><section className="bg-[#5f7489] px-4 pb-6 pt-4"><SearchBox value={query} onChange={setQuery} placeholder="城市、区域或酒店名称"/><div className="mt-3 grid grid-cols-3 gap-2 rounded-2xl bg-white p-3 text-slate-700"><label className="text-[10px] text-slate-400">入住日期<input type="date" min={today} value={checkIn} onChange={e=>setCheckIn(e.target.value)} className="mt-1 w-full bg-transparent text-xs text-slate-700 outline-none"/></label><button onClick={()=>setNights(nights%14+1)} className="border-x text-left pl-3 text-[10px] text-slate-400">住宿<p className="mt-1 text-xs text-slate-700">{nights} 晚</p></button><button onClick={()=>setGuests(guests%8+1)} className="text-left pl-2 text-[10px] text-slate-400">入住人<p className="mt-1 text-xs text-slate-700">{guests} 人</p></button></div></section>{loading?<Loading/>:items.length?<section className="space-y-4 p-4">{items.map(p=><button key={p.id} onClick={()=>onProduct(p.id)} className="w-full overflow-hidden rounded-3xl bg-white text-left shadow-sm"><SkeletonImage className="h-44 rounded-none" label={p.imageLabel}/><span className="block p-4"><span className="flex justify-between gap-3"><b className="line-clamp-2">{p.title}</b><span className="shrink-0 rounded-lg bg-[#7189a1] px-2 py-1 text-xs text-white">{p.rating}分</span></span><span className="mt-2 block text-xs text-slate-400">{p.distance} · {p.tags.join(" · ")}</span><span className="mt-3 flex items-end justify-between"><small className="text-slate-400">{checkIn} · {nights}晚</small><b className="text-xl text-[#d96f68]">{formatMoney(p.price)}<small className="font-normal text-slate-400">/晚</small></b></span></span></button>)}</section>:<Empty name="酒店房型"/>}</Shell>
}
function MarketPage({title,onBack,onProduct}:CatalogProps){
 const {query,setQuery,items,loading}=useCatalog(title);const [counts,setCounts]=useState<Record<string,number>>({});
 const change=(p:ProductData,n:number)=>{setCounts({...counts,[p.id]:Math.max(0,n)});if(n>0)add(p)};
 return <Shell title="超市" onBack={onBack}><section className="bg-[#748d7b] px-4 pb-5 pt-4"><SearchBox value={query} onChange={setQuery} placeholder="搜索生鲜、日用、零食"/></section><div className="flex gap-2 overflow-x-auto px-4 py-4">{["全部","生鲜","零食","饮料","日用"].map(x=><button key={x} className="shrink-0 rounded-full bg-white px-4 py-2 text-xs text-slate-500">{x}</button>)}</div>{loading?<Loading grid/>:items.length?<section className="grid grid-cols-2 gap-3 px-4 pb-8">{items.map(p=><article key={p.id} className="overflow-hidden rounded-3xl bg-white shadow-sm"><button onClick={()=>onProduct(p.id)} className="w-full text-left"><SkeletonImage className="h-36 rounded-none" label={p.imageLabel}/><span className="block p-3"><b className="line-clamp-2 min-h-10 text-sm">{p.title}</b><small className="mt-2 block text-slate-400">{p.sales}</small></span></button><div className="flex items-center justify-between px-3 pb-3"><b className="text-[#d96f68]">{formatMoney(p.price)}</b>{counts[p.id]?<span className="flex items-center gap-2"><button onClick={()=>setCounts({...counts,[p.id]:Math.max(0,counts[p.id]-1)})}><Minus size={15}/></button><small>{counts[p.id]}</small><button onClick={()=>change(p,counts[p.id]+1)}><Plus size={15}/></button></span>:<button onClick={()=>change(p,1)} className="flex size-8 items-center justify-center rounded-full bg-[#7189a1] text-white"><Plus size={15}/></button>}</div></article>)}</section>:<Empty name="超市商品"/>}</Shell>
}
function TravelPage({title,onBack,onProduct}:CatalogProps){
 const {query,setQuery,items,loading}=useCatalog(title);const [type,setType]=useState("精选线路");
 return <Shell title="旅游" onBack={onBack}><section className="bg-gradient-to-br from-[#68839b] to-[#879bac] px-4 pb-7 pt-5 text-white"><Plane size={25}/><h2 className="mt-3 text-2xl font-bold">探索缅甸与周边</h2><p className="mt-1 text-xs text-white/70">选择真实上架的线路、门票与当地体验</p><div className="mt-4"><SearchBox value={query} onChange={setQuery} placeholder="搜索目的地或线路"/></div></section><div className="flex gap-2 overflow-x-auto px-4 py-4">{["精选线路","当地体验","景点门票","包车"].map(x=><button key={x} onClick={()=>setType(x)} className={`shrink-0 rounded-full px-4 py-2 text-xs ${type===x?"bg-[#7189a1] text-white":"bg-white text-slate-500"}`}>{x}</button>)}</div>{loading?<Loading/>:items.length?<section className="space-y-4 px-4 pb-8">{items.map(p=><button key={p.id} onClick={()=>onProduct(p.id)} className="w-full overflow-hidden rounded-3xl bg-white text-left shadow-sm"><SkeletonImage className="h-40 rounded-none" label={p.imageLabel}/><span className="block p-4"><span className="flex gap-2">{p.tags.map(t=><small key={t} className="rounded bg-[#edf2f5] px-2 py-1 text-[#607992]">{t}</small>)}</span><b className="mt-3 line-clamp-2 block">{p.title}</b><span className="mt-2 flex items-center gap-3 text-xs text-slate-400"><CalendarDays size={14}/>需预约 <Users size={14}/>按套餐出行</span><span className="mt-4 flex items-end justify-between"><small>{p.sales}</small><b className="text-xl text-[#d96f68]">{formatMoney(p.price)}<small className="font-normal text-slate-400">起</small></b></span></span></button>)}</section>:<Empty name="旅游产品"/>}</Shell>
}
function GoodsPage({title,onBack,onProduct}:CatalogProps){
 const {query,setQuery,items,loading}=useCatalog(title);const [sort,setSort]=useState<"default"|"sales"|"price">("default");const list=useMemo(()=>sort==="default"?items:[...items].sort((a,b)=>sort==="sales"?(b.salesCount||0)-(a.salesCount||0):a.price-b.price),[items,sort]);
 return <Shell title="好物" onBack={onBack}><section className="bg-[#7189a1] px-4 pb-6 pt-4"><SearchBox value={query} onChange={setQuery} placeholder="搜索品牌或商品"/></section><div className="flex gap-2 px-4 py-4">{[["default","综合"],["sales","销量"],["price","价格"]].map(([key,label])=><button key={key} onClick={()=>setSort(key as typeof sort)} className={`rounded-full px-4 py-2 text-xs ${sort===key?"bg-[#7189a1] text-white":"bg-white text-slate-500"}`}>{label}</button>)}</div>{loading?<Loading grid/>:list.length?<section className="grid grid-cols-2 gap-3 px-4 pb-8">{list.map(p=><button key={p.id} onClick={()=>onProduct(p.id)} className="overflow-hidden rounded-3xl bg-white text-left shadow-sm"><SkeletonImage className="h-40 rounded-none" label={p.imageLabel}/><span className="block p-3">{p.isOfficial&&<small className="rounded bg-[#e8eef2] px-1.5 py-1 text-[#607992]">官方</small>}<b className="mt-2 line-clamp-2 block min-h-10 text-sm">{p.title}</b><span className="mt-2 block text-xs text-slate-400">{p.tags.slice(0,2).join(" · ")}</span><span className="mt-3 flex items-end justify-between"><b className="text-[#d96f68]">{formatMoney(p.price)}</b><small className="text-slate-400">{p.sales}</small></span></span></button>)}</section>:<Empty name="精选好物"/>}</Shell>
}
function GenericCatalog({title,onBack,onProduct}:CatalogProps){const {query,setQuery,items,loading}=useCatalog(title);return <Shell title={title} onBack={onBack}><section className="bg-[#7189a1] px-4 pb-6 pt-4"><SearchBox value={query} onChange={setQuery} placeholder={`搜索${title}`}/></section>{loading?<div className="pt-4"><Loading/></div>:items.length?<section className="space-y-3 p-4">{items.map(p=><button key={p.id} onClick={()=>onProduct(p.id)} className="flex w-full gap-3 rounded-3xl bg-white p-3 text-left"><SkeletonImage className="size-24 shrink-0 rounded-2xl" label={p.imageLabel}/><span><b className="line-clamp-2 text-sm">{p.title}</b><b className="mt-5 block text-[#d96f68]">{formatMoney(p.price)}</b></span></button>)}</section>:<Empty name={title}/>}</Shell>}
function Ride({onBack}:Props){const[destination,setDestination]=useState(""),[error,setError]=useState("");const go=()=>{if(!destination.trim())return setError("请输入目的地");window.location.assign("https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(destination.trim())+"&travelmode=driving")};return <Shell title="打车" onBack={onBack}><section className="bg-[#263846] px-4 py-6 text-white"><CarFront size={28}/><h2 className="mt-3 text-2xl font-bold">去哪里？</h2><p className="mt-2 text-sm text-white/65">使用 Google 地图网页版规划驾车路线</p></section><div className="space-y-3 p-4"><section className="rounded-3xl bg-white p-4"><div className="flex items-center gap-3 border-b pb-3"><Navigation size={18} className="text-[#7189a1]"/><span className="text-sm">当前位置</span></div><div className="mt-3 flex items-center gap-3"><MapPin size={18} className="text-[#d96f68]"/><input autoFocus value={destination} onChange={e=>setDestination(e.target.value)} placeholder="输入目的地名称或粘贴地图链接" className="min-w-0 flex-1 text-sm outline-none"/></div></section>{error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}<button onClick={go} className="w-full rounded-2xl bg-[#7189a1] py-4 text-sm font-bold text-white">打开路线导航</button></div></Shell>}
function Recharge({onBack}:Props){return <Shell title="充值" onBack={onBack}><section className="bg-[#7189a1] px-5 py-7 text-white"><WalletCards size={28}/><h2 className="mt-3 text-xl font-bold">充值服务</h2></section><section className="m-4 rounded-3xl bg-white p-5"><ShieldCheck size={24} className="text-[#7189a1]"/><h3 className="mt-3 font-bold">充值渠道尚未接入</h3><p className="mt-2 text-sm leading-6 text-slate-500">获得运营商或支付服务商正式接口前，系统不会收款。</p><button onClick={onBack} className="mt-5 w-full rounded-2xl bg-slate-100 py-3 text-sm">返回</button></section></Shell>}
function Flash({onBack}:Props){return <Shell title="闪兑" onBack={onBack} dark><section className="px-5 py-8"><Zap size={28}/><h2 className="mt-4 text-2xl font-bold">闪兑暂未开放</h2><p className="mt-3 text-sm leading-6 text-white/60">汇率、收款地址和链上发货接口接入前不会接受订单。</p><button onClick={onBack} className="mt-7 w-full rounded-2xl bg-white/10 py-4 text-sm">返回</button></section></Shell>}
const more=["电影","洗衣","维修","搬家","门票","火车票","咖啡","生活缴费"];
function More({onBack,onService}:Props){return <Shell title="更多服务" onBack={onBack}><section className="grid grid-cols-2 gap-3 p-4">{more.map(name=><button key={name} onClick={()=>onService?.(name)} className="flex min-h-28 flex-col items-start justify-between rounded-3xl bg-white p-4 text-left shadow-sm"><span className="flex size-10 items-center justify-center rounded-2xl bg-[#edf2f5] text-[#7189a1]"><Store size={20}/></span><span><b className="block text-sm">{name}</b><small className="mt-1 block text-slate-400">查看已入驻服务</small></span></button>)}</section></Shell>}
export function ServicePage(p:Props){const title=p.title||"服务";if(title==="外卖")return <FoodPage title={title} onBack={p.onBack} onProduct={p.onProduct}/>;if(title==="酒店")return <HotelPage title={title} onBack={p.onBack} onProduct={p.onProduct}/>;if(title==="超市")return <MarketPage title={title} onBack={p.onBack} onProduct={p.onProduct}/>;if(title==="旅游")return <TravelPage title={title} onBack={p.onBack} onProduct={p.onProduct}/>;if(title==="好物")return <GoodsPage title={title} onBack={p.onBack} onProduct={p.onProduct}/>;if(title==="打车")return <Ride {...p}/>;if(title==="充值")return <Recharge {...p}/>;if(title==="闪兑")return <Flash {...p}/>;if(title==="更多")return <More {...p}/>;return <GenericCatalog title={title} onBack={p.onBack} onProduct={p.onProduct}/>}
